### ISSUE TITLE
Delete node for the path "users/Students" where key "userId" from Students

### ISSUE THREAD

**Issue by Mohankumar28** [kreait/firebase-php#114]
Hi,

Need to delete a node using  a property called userId.
How we can do this. Please help.

```php
$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri('https:/xxxxyyy.firebaseio.com')
    ->create();

$database = $firebase->getDatabase();
$user_id = $_POST['user_id'];
$stu = $database->getReference('users/Students')
			    ->orderByChild('userId')
				->equalTo($user_id)
				->remove();
```

**Comment by jeromegamez** [comment]
`orderByChild()` and `equalTo()` return `Query` objects, but you can only remove References. You need to determine the key of the user you want to delete beforehand, so that you can do something like `$database->getReference('users/Students/<key>')->remove()` - which is not specific to this library.

I am closing this issue now, but please feel free to join the Firebase Community Slack at https://firebase-community.appspot.com/ where other Firebase users can certainly help.
