### ISSUE TITLE
getAccountInfo methods or getUser Token or FirebaseTokenID

### ISSUE THREAD

**Issue by canhkieu** [kreait/firebase-php#127]
I used getAccountInfo to get UserData by idToken (FirebaseToken). Could you provide a same methods to get UserData by FirebaseToken or Facebook AccessToken - Google AccessToken (oAuth Token).

https://firebase.google.com/docs/reference/rest/auth/#section-get-account-info

**Comment by jeromegamez** [comment]
This is not provided directly by the Rest API, but I already have an idea how I can implement a workaround, so stay tuned :).

**Comment by jaydeepgiri** [comment]
hello @jeromegamez bro, I'm using firebase authentication on my server. Allowing users to signup & signin with firebase `UID`. Requests come from an android APP via an API, where user is validated and registered to firebase using android app and than sent the information to server. On the server end without validating the request, we assume that the user is valid and we insert the record into the database. 

Now due to this scenario, Our server is facing some invalid requests to API from unknown sources. To prevent this we just want to verify the UID of the user passed to API is valid or not. 
How can this be done? Please help.

I have installed firebase php SDK and tried to solve the issue by referring the docs, but couldn't solve it.
Kindly your help will be appreciated. 

Thanks

**Comment by jeromegamez** [comment]
@jaydeepgiri 

While you can’t prevent your API from being accessed by unknown sources, you can verify that the requests are valid by using ID tokens.

Your android app knows that the current user is valid, but the server does not, so UIDs are not enough.

You can get the ID Token of the current user by implementing the steps described in https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients

Such an ID Token can then be verified on the server side by following https://firebase-php.readthedocs.io/en/stable/authentication.html#verify-a-firebase-id-token

**Comment by jaydeepgiri** [comment]
@jeromegamez Thanks bro. For a while I found the solution to stop the hacker from registering the data into my database by verifying the UID. I'll surely consider the advice which you said.

**Comment by jaydeepgiri** [comment]
@jeromegamez Hello, I used the technique you mentioned. now that's working fine, but there is no way to set ID token expiration time. Default time is 1 hour, which may again cause some issues. Is there any way to set user defined expiration time for ID token on android side?

Thank you

**Comment by jeromegamez** [comment]
@jaydeepgiri I remember that it was once possible, but not anymore - the official SDKs also set the expiration time to 1 hour (see https://github.com/firebase/firebase-admin-node/blob/master/src/auth/token-generator.ts#L294) .

It might come back in a future (major) release, but I can't promise that.
