### ISSUE TITLE
Firebase server time and Goolge compute engine server time are slightly different.

### ISSUE THREAD

**Issue by nurfgun** [kreait/firebase-php#140]
#### 1. Which version of `kreait/firebase-php` are you using?

3.1.2

#### 2. Which version of PHP are you using?

7.1

#### 3. What's the issue?

Firebase server time seems to be ahead of the time of our Google cloud compute engines behind load balancer or GCEs are behind firebase server time.

#### 4. Code that lead to the issue

Right after a user logs in with firebase on the front side thru the web sdk, the user starts sending requests to our GCE server with firebase id token. Here comes the issue. The firebase-php verifyIdToken method in GCE server sees this fresh token and returns the "This token has been issued in the future" error for first several requests.

I've just made users wait the amount of time difference so far and now I'm writing a custom verification function on the php server side.

would GCE's using NTP other than server metadata.google.internal be a solution?
It seems to me Firebase doesn't provide public NTP servers nor use metadata.google.internal as its NTP servers.

Many thanks in advance for your support :)

**Comment by jeromegamez** [comment]
I'm torn on this: if the time is not correct on one of the environments (GCE/Server or Firebase), I would normally say, that this has to be fixed in the environment. The purpose of the token verification is to expose such issues and to fail if something is influencing the security in a negative way.

Here's my proposal: I will add add a `getToken()` method to the `InvalidIdToken` exception and add more specific exception types. This means that you would be able to work with/use the token even if the verification failed, so it could look something like this:

```php
 
try {
    $idToken = $auth->verifyIdToken($idTokenString);
} catch (IdTokenIssuedInTheFuture $e) {
    $idToken = $e->getUnverifiedToken(); // or $e->getInsecureIdToken();
}
``` 

Would that be something that you could work with?

**Comment by jeromegamez** [comment]
@alexswe1 Is https://github.com/kreait/firebase-php/issues/140#issuecomment-350273278 something you could work with?

**Comment by jeromegamez** [comment]
@alekswe1 @nurfgun [Release 3.6.0](https://github.com/kreait/firebase-php/releases/tag/3.6.0) now includes this. I think this is a good compromise between letting you work around the issue and me not weakening the purpose of ID verification itself :).

**Comment by alexswe1** [comment]
For me I am not sure the solution is ok. The running code will probably alway end up going into the exception part of the try catch for me at least. I cannot change the time or date on the google token server and I have a php hosted with my web page provider, so cannot change the date on that server either. Even if the time is 1 second into the future the exception might also be trigged. In your code, I think it would be better to send in a parameter to verifyIdToken where you can switch off the check for token issue date (default could be false for check). That way if you want to check that part of the token you could (but risk that exception to be triggered), and skip it otherwise. The reason why I think it is better for it to be false initially, is that if someone start using the php firebase library, the code might all of a sudden start failing if the clock on one of the servers go out of sync either temporarily or permanent and the code will fail for the implemented service of the user.

**Comment by nurfgun** [comment]
Thanks @jeromegamez ! this will do for me.

**Comment by kaoz70** [comment]
What I did was catch an IssuedInTheFuture exception (use Firebase\Auth\Token\Exception\IssuedInTheFuture)

In my case the server needs to be in GMT-5 timezone, but the token was created in UTC, wich was giving me a 5 hour diference in the future. It would be nice if you pass the timezone to the Verifier constructor or the verifyIdToken() method.

**Comment by jeromegamez** [comment]
Time... it always causes me headaches :D. I had assumed, that different timezone should not matter, because only timestamps are used, for example:

```php
$tz = new \DateTimeZone('America/Los_Angeles');
$tzUtc = new \DateTimeZone('UTC');

date_default_timezone_set($tz->getName());
echo time().PHP_EOL;

date_default_timezone_set($tzUtc->getName());
echo time().PHP_EOL;
```

gives me the same result. 

Could you create a branch based on https://github.com/kreait/firebase-tokens-php and add a failing test that I can then examine further?

**Comment by martiendt** [comment]
Hi, is this problem fixed ? 
because i still get this problem

this is my code
```
try {
    $verifiedIdToken = $this->firebase->getAuth()->verifyIdToken($idTokenString);
    $uid = $verifiedIdToken->getClaim('sub');
    $user = $this->firebase->getAuth()->getUser($uid);

    return $user;
} catch (InvalidToken $e) {
    return $e->getMessage();
}
```

But often i got this error "Issued in the future" Error. My workaround is comment this code from Verifier.php, and now i can login with firebase google auth

```
if ($token->getClaim('iat') > time()) {
    throw new IssuedInTheFuture($token);
}
```

**Comment by jeromegamez** [comment]
[4.9.0](https://github.com/kreait/firebase-php/releases/tag/4.9.0) ([Documentation](https://firebase-php.readthedocs.io/en/latest/authentication.html#verify-a-firebase-id-token)) should fix the issue for special use cases.

I have to add: it's not an issue of the library, and fixing the time is preferable to using the new flag. But here you are :)
