### ISSUE TITLE
Security issue (redacted)

### ISSUE THREAD

**Issue by hernandev** [kreait/firebase-php#150]
(redacted)

**Comment by jeromegamez** [comment]
You are right, thank you for bringing this to my attention. I will edit the text of your submission to avoid a malicious person trying to exploit it and work on a fix and new release right away.

Thanks again!

**Comment by hernandev** [comment]
@jeromegamez Things like this happens to the best ones.

My Kudos for treating it seriously enough.
 
Let's for now delete the issue, since github keeps tracks of title.

**Comment by hernandev** [comment]
drop me an email at diego@hernandev.com if you need any help with it. Thanks

**Comment by jeromegamez** [comment]
It's not possible to delete issues on GitHub, but this shouldn't be too much of an issue - this library is not SO popular and Google certainly hasn't picked it up yet. 

Could you have a look at #151, please? Meanwhile I will close this issue and hope that a lot of issues come in in the next days so that it can be buried :)
