### ISSUE TITLE
Firebase requests too slow

### ISSUE THREAD

**Issue by mag1cdagger** [kreait/firebase-php#165]
#### 1. Which version of `kreait/firebase-php` are you using?
3.9.3

#### 2. Which version of PHP are you using?
7.2.1

#### 2.1 Which CURL version?
7.56.0

#### 2.2 Which guzzle versions?
6.3.0 guzzlehttp/guzzle
1.4.2 guzzlehttp/psr7
1.3.1 guzzlehttp/promises

#### 2.3 Tested Environments
- xampp 7.2.1 (windows 7)
- docker container with php 7.1 apache (linux)

#### 3. What's the issue?
The first request to firebase database takes about ~ 7 seconds. Every request after that takes about ~1 second. When I make the same request in nodejs or javascript, the first request takes about ~1 sec and all following one about 0.2 seconds. So my requests with that library in php takes way too long and I have no idea why. I tested it without any framework and on different networks (home & workplace), also on docker and xampp. The slow function seems to be the getValue() function.

#### 4. Code that lead to the issue

```
<?php
require __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/firebaseConfig.json');

$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
    ->withDatabaseUri('https://***********.firebaseio.com')
    ->create();

$database = $firebase->getDatabase();

$result = $database->getReference("watchlists/user/watchlist1/entries");
$value = $result->getValue();

var_dump($value);
?>
```

**Comment by jeromegamez** [comment]
The PHP SDK will re-create a new connection to the Firebase REST API on each request and download the whole dataset. Because each run of the script is a new process, we have no means of re-using an existing HTTP connection.

When `$value = $result->getValue();` is executed twice in the same script/run, the Guzzle connection should be persistent and performance should be a little bit better.

I am not sure if this helps, but I hope it does.

**Comment by jeromegamez** [comment]
It's absolutely possible that the official NodeJS/JS libraries optimize something under the hood that I'm not aware right now, but I am already working on 4.0 and a future 5.0 (with HTTP Promises) which hopefully will increase the performance further.

**Comment by mag1cdagger** [comment]
In my case im always executing just 1 query, so it takes always about 1 minute to finish an action (I'm creating an API, which connects to firebase). I could save some query snapshots in a session, but the updates are a bit annoying sometimes. Is there anything i could do to get your SDK  re-use the http-connection?

btw. I've tested the 4.0 SDK and there's no performance increase till now :/

**Comment by jeromegamez** [comment]
In that case there is not much we can do about that except caching the results returned from the Rest API in a local memcache or redis. But you should be aware that those results can be outdated rather quickly.

Firebase updates will also be slower then in the node/js libraries, because the requests will have to travel from: API-Access -> server backend -> Firebase -> server backend -> API-Result. This will always be slower than using the official libraries.

**Comment by jeromegamez** [comment]
I will close this issue now because I think it is not related to the library itself, but feel free to add further comments any time!
