### ISSUE TITLE
Cannot verify custom token

### ISSUE THREAD

**Issue by aspelund** [kreait/firebase-php#169]
#### 1. Which version of `kreait/firebase-php` are you using?

3.9.3

#### 2. Which version of PHP are you using?

PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )

#### 3. What's the issue?

Tokens created using createCustomToken cannot be verified using verifyIdToken. Error message is The header "kid" is missing.

Googling about the header kid it seems as if that one is actually an optional part of the token. (http://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName).

#### 4. Code that lead to the issue
```
// Code to create token:
    	$auth = $firebase->getAuth();
    	$uid = $user->id;
    	$claims = ['foo' => 'bar'];

    	$date = new DateTime();
		$date->add(new DateInterval('P1Y'));		
    	$customToken = $auth->createCustomToken($uid, $claims, $date);

// Code to verify token (this breaks)
        $token = $auth->verifyIdToken($jwt);

```

**Comment by jeromegamez** [comment]
That's correct, you cannot verify a **custom** token, that's why I named the methods so clearly 😅.

Custom Tokens are to be exchanged for an ID token by sending them to the Firebase REST API which will send an ID token back, which then can be verified.

Custom Token != ID Token

See also https://firebase-php.readthedocs.io/en/stable/authentication.html#verify-a-firebase-id-token :

<img width="731" src="https://user-images.githubusercontent.com/67554/36421891-80cba6aa-163a-11e8-9e46-845cf21cf0d7.png">

**Comment by MGParisi** [comment]
How do we get the idTokenString?
