### ISSUE TITLE
Call to undefined method Kreait\Firebase::getStorage()

### ISSUE THREAD

**Issue by tehjnito** [kreait/firebase-php#190]
Using version 4.0.0 and php version 7.0.10

Ive been getting an undefined method error when I try to get the storage object

````

/* the regular initializing stuff */
$firebase->getStorage()

````

However the 'getDatabase()' and the 'getAuth()' works perfectly fine......so whats going on?

**Comment by jeromegamez** [comment]
That's indeed strange - as you can see in https://github.com/kreait/firebase-php/blob/master/src/Firebase.php, the method is there, and the Firebase class can't be instantiated without the storage being passed as a dependency.

Without more information, I can't figure out what's going on - could you please provide the output of `composer show` and the contents of your `composer.json` file?

**Comment by jeromegamez** [comment]
And the full stack trace of the error, please :)

**Comment by tehjnito** [comment]
I believe I've found out what was wrong.

I checked the firebase.php file in the repository and noticed that it was different from what was in my project.
The documentation at [firebase-php.readthedocs.io](https://firebase-php.readthedocs.io/en/latest/overview.html) instructed to install with `composer require kreait/firebase-php ^4.0`
Once I checked the files here on Github it clicked that the problem was that I was installing an earlier version of the library, so I just omitted the `^4.0` which gave me the latest version.
So I guess basically you should update that page on [firebase-php.readthedocs.io](https://firebase-php.readthedocs.io/en/latest/overview.html) before someone else runs into the same problem lol

thank you for getting back to me though, it wouldn't have realized until you posted the link....

**Comment by jeromegamez** [comment]
Glad you got it working, although I can't reproduce the issue that requiring the library with `^4.0` installs a version smaller than 4.0 (which it shouldn't)

I added the version constraint in the docs, because in the past, people often didn't get the latest version because of an older PHP Version (composer always installs the latest *supported* version). By providing the version constraint, a developer gets an error when they try to install version 4.x on let's say PHP 5.6 (without the version constraint, composer would automatically install 2.x).

So I will keep the documentation as is, but this issue here helps me asking the right questions in the future, and I will update the issue template to make clearer what I need to be able to help (e.g had you followed the advice to do a `composer show kreait/firebase-php` you would have noticed the diverging versions before submitting the issue ^^.

Thanks for laying out what fixed the issue for you, this will certainly help others in the future! 🌺
