### ISSUE TITLE
Getting 401, Permission denied error on read data from firebase

### ISSUE THREAD

**Issue by exleedo** [kreait/firebase-php#197]
Hi, firstly thank you so much for such a great library. But I am getting an error using it.

I am using php PHP 7.2.5 and version * 4.7.1 of the library, and I am getting a 401 , permission denied error. I checked the role with 'Project Editor' and 'Project Owner' both, and the Database rules for read & write are both true. 

But when I try to read the data, I get 401 , permission denied error.

The weird thing is that I do get the data from firebase but library returns 401 error.

In the middleware 

```public static function ensureJsonSuffix(): callable
    {
        return function (callable $handler) {
            return function (RequestInterface $request, array $options = []) use ($handler) {
                $uri = $request->getUri();
                $path = $uri->getPath();

                if ('.json' !== substr($path, -5)) {
                    /** @noinspection ExceptionsAnnotatingAndHandlingInspection */
                    $uri = $uri->withPath($path.'.json');
                    $request = $request->withUri($uri);
                }

                return $handler($request, $options);
            };
        };
}
```

where there is `$request = $request->withUri($uri);` I get the data from firebase, and I can print it there. But the next call at the bottom of the function `return $handler($request, $options);` returns 401 error.

Bellow is the code that cause the issue : 

```$serviceAccount = ServiceAccount::fromJsonFile(base_path("my-service-account.json"));
    
        
        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->withDatabaseUri('Database_URI')
            ->create();
    
        $database = $firebase->getDatabase();
    
        $testData = $database
            ->getReference('testData')->getSnapshot();

          var_dump($testData)
```

**Comment by jeromegamez** [comment]
Hey @exleedo and thank you for reporting this issue!

The 401 error is still an indication that the used service account doesn't match the project  you are accessing or hasn't the needed permissions, and the exception is thrown by Google's Authentication middleware when processing the server response.

The database rules don't apply when using the Admin SDK, because the Service Account grants unrestricted admin rights.

Could you please try the following:

1. Look inside the used service account JSON file and check if the field `project_id` matches your database URI. Usually, if the project id is `myproject`, the database URI is`myproject.firebaseio.com`. If both are the same, you can remove the `withDatabaseUri()` line - the library will then determine the database URI automatically.
2. Try creating a new service account JSON file by accessing https://console.firebase.google.com/project/_/settings/serviceaccounts/adminsdk and then clicking "Generate new private key". Then reference this file when bootstrapping the SDK in your script.

**Comment by exleedo** [comment]
Thanks @jeromegamez for prompt reply. 

1- By doing this, it doesn't give me the error now, but it also doesn't bring the data.

2- Same thing with the new key as well.

**Comment by exleedo** [comment]
Thanks @jeromegamez for a quick reply. thank you so much. Deleting the old service account, and recreating a new service account with 'Project Editor' permissions worked this time. It works with & without the `withDatabaseUri()` .

Thank you so much for your help & this amazing library.

**Comment by jeromegamez** [comment]
Glad it worked out, thank you for the kind words! 🌺
