### ISSUE TITLE
Pagination - List of users

### ISSUE THREAD

**Issue by front-stream** [kreait/firebase-php#203]
Great tool! I have small question: Is it possible to paginate list of users? https://firebase-php.readthedocs.io/en/latest/user-management.html#list-users

**Comment by jeromegamez** [comment]
Unfortunately the REST API doesn't support pagination - that's why I went with the Generator to be able to still fetch the users with decent speed.

You could wrap the call in a pagination class, but if you were to fetch something like `?size=100&page=3`, this would still result in 3 subsequent calls to the API.
