### ISSUE TITLE
Add Exponential Backoff

### ISSUE THREAD

**Issue by raiffeisennet** [kreait/firebase-php#264]
As I am getting 503 responses on sending push messages, i would like to ask you to implement an exponential backoff which is required by some Google APIs like it was done for FCMSharp:

https://github.com/bytefish/FcmSharp/issues/31

Thank you

**Comment by jeromegamez** [comment]
You can add Guzzle Middlewares as described here: https://firebase-php.readthedocs.io/en/stable/setup.html?highlight=middleware#http-client-options-and-middlewares

Guzzle ships with a retry middleware that you could use https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L169-L174 / https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php

I'd like to keep this optional instead of baking it into the SDK - others might prefer to be able to handle errors as they happen.
