### ISSUE TITLE
Permission denied using $firebase->set ～5% of the times

### ISSUE THREAD

**Issue by Mygod** [kreait/firebase-php#29]
Here's the log with sensitive information removed:

```
2016-08-15T11:34:42.296710+00:00 app[web.1]: [15-Aug-2016 11:34:42 UTC] PHP Fatal error:  Uncaught Kreait\Firebase\Exception\FirebaseException: Server error (403) for URL https://*.firebaseio.com/*.json with data "*": Permission denied. in /app/vendor/kreait/firebase-php/src/Exception/FirebaseException.php:82
2016-08-15T11:34:42.296726+00:00 app[web.1]: Stack trace:
2016-08-15T11:34:42.296830+00:00 app[web.1]: #0 /app/vendor/kreait/firebase-php/src/Firebase.php(249): Kreait\Firebase\Exception\FirebaseException::httpError(Object(Ivory\HttpAdapter\Message\Request), Object(Ivory\HttpAdapter\Message\Response))
2016-08-15T11:34:42.296917+00:00 app[web.1]: #1 /app/vendor/kreait/firebase-php/src/Firebase.php(132): Kreait\Firebase\Firebase->send('https://*.f...', 'PUT', Array)
2016-08-15T11:34:42.296992+00:00 app[web.1]: #2 /app/*/api.php(176): Kreait\Firebase\Firebase->set(Array, '*/me...')
2016-08-15T11:34:42.297037+00:00 app[web.1]: #3 /app/*/api.php(184): onReceive()
2016-08-15T11:34:42.297040+00:00 app[web.1]: #4 {main}
2016-08-15T11:34:42.297112+00:00 app[web.1]:   thrown in /app/vendor/kreait/firebase-php/src/Exception/FirebaseException.php on line 82
2016-08-15T11:34:42.297290+00:00 app[web.1]: 10.69.216.189 - - [15/Aug/2016:11:34:39 +0000] "POST /* HTTP/1.1" 500 706 "-" "Mozilla/4.0
```

**Comment by jeromegamez** [comment]
Could you show me a code snippet so that a I can try to replicate the error? At the moment, I am assuming that you are performing multiple sets in a loop, is that right? Also, are you using custom authentication, and do you have database rules set up for the leaf you're writing to?

**Comment by Mygod** [comment]
No but I have 2 `set`s per requests and there's a request like every ~5 seconds. Maybe there are two concurrent `set` going on at the same time? As I've said I can't reproduce this error 100% of the times either. :/

Also I'm running 1.1 version.

**Comment by jeromegamez** [comment]
I would like to help find the issue, but without a code example, this is going to be difficult. There's no rate limitation in Firebase that I'm aware of, so here are some wild guesses:

- Are you writing to the same node (or child of the node) when performing the two requests? Like, the first `set` goes to "path/to/child", and the second goes to "path/to/child/grandchild"?
- Are you adding a lot of children to the same parent? If so, I suggest using `->push()` instead of `->set()`. If you already have some kind of unique ID in your original dataset, you could at it to the child's data or create an additional mapping.

Please let me know if I can be of further assistance - the optimal way would be to create a pull request with an added test which fails (even if it is just in 5% of all cases), then I would have something to work with - a simple code snippet here in the issue comments would be fine as well :)

**Comment by Mygod** [comment]
Oh okay. Here's a simplified example...

```
$config = new Configuration();
$config->setAuthConfigFile(dirname(__FILE__) . '/../data/my-domain-admin.json');

$firebase = new Firebase('https://my-domain.firebaseio.com', $config);

$url = 'first/second/' . $uniqueIdFrom_POST;
$firebase->set(['pending' => true], $url);
$details = some_function_that_takes_some_time_to_return(); // returns an array of 100-2k bytes, also generates response
$firebase->set($details, $url); // use set so that pending: true will be removed
```

All my rules are unrelated to `first`, like these:

```
{
  "rules": {
    "users": {
      "$uid": {
        "protected": {
          ".read": "auth !== null && auth.uid === $uid"
        },
        ".write": "auth !== null && auth.uid === $uid"
      },
      ".read": true,
      ".indexOn": "score"
    },
    "anotherField": {
      ".read": true
    }
  }
}
```

And it works fine for most of the times.

**Comment by Mygod** [comment]
Oh sorry I forgot a `$firebase->get` call before the first `$firebase->set`. If it reads `pending = true`, the execution will stop.

**Comment by Mygod** [comment]
Hmm sounds like oauth-token expiring might be the issue.

P.S. Wow how did your Wi-Fi managed to break though... :joy_cat:

**Comment by jeromegamez** [comment]
The problem with 1.x (and one of the reasons for 2.x) is that the google authentication is based on Guzzle, but 1.x uses the (now way outdated) Ivory Http Adapter, so these are two seperate methods that I'm trying to combine. If Oauth turns out to actually be the issue, The only solution will be to integrate this workaround into the 1.x core, because I can't change the 1.x dependencies without causing a BC break.

But I'll keep looking - in the meantime, please consider switching to 2.0 :) - it's much nicer to work with and I consider it stable... The current beta status is only a timeframe in which I want to finish the documentation :)

**Comment by jeromegamez** [comment]
It's not the the access/refresh token - I just modified 1.x to fetch a new token on every request (instead of using an existing token until it expires) and everything worked fine.

The Google OAuth PHP library refreshes a token automatically if it expires in the next 30 seconds, so this should not be the issue here.

Btw, here's the code I'm testing with:

```php
require_once __DIR__.'/vendor/autoload.php';

use Kreait\Firebase\Configuration;
use Kreait\Firebase\Firebase;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

$logger = new Logger('firebase-php');
$logger->pushHandler(new StreamHandler('firebase.log', Logger::WARNING));

$config = new Configuration();
$config->setAuthConfigFile(__DIR__ . '/google-service-account.json');
$config->setLogger($logger);

$firebase = new Firebase('https://project-id.firebaseio.com', $config);

$data = [];
for ($i = 0; $i < 2000; $i++) {
    $data[uniqid('', false)] = uniqid('', false);
}

$counter = 0;

while (true) {
    try {
        echo '#'.++$counter;

        $url = 'test-issue-29/first/second/'.uniqid('', false);

        echo ' pending... ';
        $firebase->set(['pending' => true], $url);

        echo ' setting... ';
        $firebase->set($data, $url);

        echo ' done!'.PHP_EOL;
    } catch (\Kreait\Firebase\Exception\FirebaseException $e) {
        print_r($e->getResponse()->getHeaders());
        exit;
    }
}
```
