### ISSUE TITLE
Firebase Phone Authentication 

### ISSUE THREAD

**Issue by vkiranmaniya** [kreait/firebase-php#293]
## The problem

I want to Authenticate my Users with their phone number. There are a broad explanation and Docs about it in JS, but I didn't find anything about User Auth in Firebase-php Docs. I'm Using Verify Id Tokens and other things in my production app and it works fine. What About Phone Auth? is it possible with this SDK?

## Environment

- PHP Version : 7.2.11
- Firebase PHP SDK version: 4.18.0

**Comment by jeromegamez** [comment]
I'm not sure this makes sense in the PHP backend context, as you would need to create a verification code to be sent to the user and then handling the flow between your client application and the server backend, and ensuring that everything is done in a secure way.

I think it would be a better solution to verify phone numbers directly on the client side with the help of the official client SDKs

* https://firebase.google.com/docs/auth/web/phone-auth
* https://firebase.google.com/docs/auth/android/phone-auth
* https://firebase.google.com/docs/auth/ios/phone-auth

**Comment by GENL** [comment]
I have the same remark. I build a php(laravel) api for an android mobile app. I can of course make the phone auth to the client side but it does not guarantee the backend that the code has been verified as some can consume my api with something like Postman, create a user without verifying his phone. If I can verify the phone the server side this problem is solved. Even if I do not save the code in the database, I just need to be sure that the code was verifed.

**Comment by jeromegamez** [comment]
Firebase doesn't provide the means to do phone auth verification on the backend. If there's a solution, it is out of the scope of this SDK.

I've written a lengthy comment on this exact topic on StackOverflow - it's from March 2019, but I still stand by it :) 

https://stackoverflow.com/questions/55121166/phone-authentication-validation-from-server-side-firebase-php/55171266#55171266

As soon as one of the official Firebase Admin SDKs provide such a solution, I might reconsider :)

**Comment by GENL** [comment]
I already have my own authentication system. The authentication of the Firebase phone to the backend would be mainly used for sending SMS.
