### ISSUE TITLE
Use the Firebase batch APIs for Multicast messages

### ISSUE THREAD

**Issue by jeromegamez** [kreait/firebase-php#302]
Follow up to #261 

At the moment, sending a message to multiple recipients results in one API request per recipient.

Instead, we should use the Firebase Batch API to reduce the number of requests, see

- https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/batch-request.ts
- https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging-api-request.ts
- https://medium.com/@hiranya911/firebase-introducing-the-cloud-messaging-batch-apis-in-the-admin-sdk-2a3443c412d3

**Comment by yash3040** [comment]
Thanks for this.
But now, what about sending message to multiple topics?
Because when i checked the sendMulticast() function code, you have statically defined the target as a MessageTarget::TOKEN.
So how can we send a message to multiple topics?

**Comment by jeromegamez** [comment]
@yash3040 You can use conditionals for that: https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#send-conditional-messages

**Comment by yash3040** [comment]
Thanks for the quick reply.
But i wanted a function like sendTopicMulticast(). It would be better if we could just pass the topics array to it rather than concatenating each topic in condition string using foreach and then removing trailing OR(||) sign from it.
But no worries. I was and i will use the https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#send-conditional-messages.

BTW, you could make a function like that and do the "concatenating each topic in condition string using foreach and then removing trailing OR(||) sign from it" logic in it. Just for easy usage.

But anyway this is a great package and many thanks to you. :)

**Comment by PokeGuys** [comment]
I am working on it. Here is the PR #307

**Comment by Techiedie** [comment]
@jeromegamez  please solve my problem #310

**Comment by jeromegamez** [comment]
@Techiedie Please don't ping me in unrelated other issues.

**Comment by jeromegamez** [comment]
Implemented with 7713753c296a6d0cc7ab514171bc513bc0ec8a1c

The next release (4.29.0) is going to be an especially nice one. I need make some changes before, so it will probably take a couple of days, but if you already want to check it out, require `dev-master` in your `composer.json` files :)

**Comment by jeromegamez** [comment]
@yash3040 Release [4.29.0](https://github.com/kreait/firebase-php/releases/tag/4.29.0) is out and uses the Batch APIs for better performance. 

Thanks again to @PokeGuys for the important groundwork in #307!

**Comment by abdulmatinsanni** [comment]
I'm so happy about this. 👍

**Comment by ssi-anik** [comment]
I tried sending push to a batch of tokens and I found that it request `n` times to process those tokens. Any way to overcome this?

**Comment by jeromegamez** [comment]
Code or or didn't happen 😃. Please join the Discord server for this, it's probably an usage issue, not a problem within the SDK.

Have you looked at https://firebase-php.readthedocs.io/en/5.12.0/cloud-messaging.html#send-messages-to-multiple-devices-multicast ?
