### ISSUE TITLE
Recipient of the message is not set

### ISSUE THREAD

**Issue by L-Y** [kreait/firebase-php#308]
I have a question in here:

I have push message to many devices use sendMulticast , It can push sucess,but return 400 ```
error!
{
  "error": {
    "code": 400,
    "message": "Recipient of the message is not set.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message",
            "description": "Recipient of the message is not set."
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT"
      }
    ]
  }
}
```

**Comment by jeromegamez** [comment]
What is the message you‘re trying to send, and how do you create it and call the sendMulticast() method?

**Comment by L-Y** [comment]
@jeromegamez yes  my code is:
```
$pushTokens = ['token1',token2'];
        $firebase = (new Firebase\Factory())->create();
        $messaging = $firebase->getMessaging();
        $message = CloudMessage::new()
            ->withNotification(Firebase\Messaging\Notification::create('title', 'body'))
            ->withData($data);

        $tryMsg = $messaging->sendMulticast($message,$pushTokens);
        try {
            $messaging->validate($message);
        } catch (Firebase\Exception\Messaging\InvalidMessage $e) {
            $tryMsg = $e->errors();
        }
```

**Comment by jeromegamez** [comment]
The order is a little bit messed up - you are currently first sending, and only after that validating the message (when it's already "too late").

If you call `$messaging->validate()` on the message as it is, the Firebase API will return the error you have, because `$message` doesn't include a recipient, so the error you are receiving is correct.

`$messaging->sendMulticast()` will loop over each token you provided and call `withTarget()` on the message to make it valid, and send the messages.

`$messaging->sendMulticast()` will also not throw exception but always return a `MulticastSendReport` - please see the documentation at https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html#send-messages-to-multiple-devices-multicast for more information on how to use it.

**Comment by jeromegamez** [comment]
If you want to validate the messages to all tokens before sending them, this is what you currently would have to do:

```php
foreach ($pushTokens as $token) {
    try {
        $messaging->validate($message->withChangedTarget('token', $token));
    } catch (MessagingException $e) {
        // for example:
        print_r($e->errors();
    }
}
```

**Comment by L-Y** [comment]
@jeromegamez  Thank you very much, I understand!
