### ISSUE TITLE
How can i get list key name

### ISSUE THREAD

**Issue by dungphanxuan** [kreait/firebase-php#32]
Hello, i'm new firebase. So now i need get list key. How can i do it. thank
![screenshot_1](https://cloud.githubusercontent.com/assets/10725732/17722383/f0f4dda8-645b-11e6-9e21-a8b41dc3cba2.png)

**Comment by jeromegamez** [comment]
For future reference: The Firebase REST API doesn't provide a direct way to get the keys of a result set directly.

The fastest way would be to use a shallow Query (which means that the resultset returns an "empty" array in the form of

```php
[
    'key_1' => true,
    'key_2' => true,
    'key_3' => true
]
```
Then you can use an `array_keys()` on it:

### 1.x

```php
use Kreait\Firebase\Query;
$query = new Query();
$query->shallow(true);

$keys = array_keys($firebase->query('path/to/child', $query));
```

### 2.x
```php
$keys = array_keys($db->getReference('/')->shallow()->getValue());
```

If you have to filter your results beforehand, `shallow()` will not work, because the REST API doesn't let you combine it with other filters. In this case, you have to perform a normal Query and then again, use `array_keys()` with it.

**Comment by dungphanxuan** [comment]
that very userfull, i will try, because, i think get all data so app will slow.
Thank you for you help.
