### ISSUE TITLE
Add documentation showing how to use custom JWT's with this library

### ISSUE THREAD

**Issue by dotstormz** [kreait/firebase-php#33]
Hey it would be really awesome if you could outline if your implementation supports custom JWT's and how you would foresee these integrating? I am happy to contribute to the project and write documentation etc.

Still trying to wrap my head around the final touches and any help that could lead to me taking the time to contribute would be awesome.

**Comment by jeromegamez** [comment]
Hi Greg, and thank you for your Feedback. The library does indeed support custom tokens, you can find the implementation here:

https://github.com/kreait/firebase-php/blob/master/src/Firebase/V2/Http/Auth/CustomToken.php

However, custom tokens are only needed when authenticating with the database through a database secret, which has to be considered a legacy method since Firebase added Service Account authentication (hence the V2 namespace).

Since V3, the "impersonation" of a user is called "authentication override", of which you can find the implementation here:

https://github.com/kreait/firebase-php/blob/master/src/Firebase/V3/Auth/CustomToken.php

**Comment by jeromegamez** [comment]
As a matter of fact, I have started extending the docs just yesterday, so expect a more detailed usage example on ReadTheDocs soon - in short: you can use the method `asUserWithClaims(string $uid, array $claims = [])` on any Firebase or Database instance.

**Comment by jeromegamez** [comment]
Hey @dotstormz,

I just uploaded the authentication docs, you can find them here: http://firebase-php.readthedocs.io/en/latest/authentication.html#authentication-overrides-a-k-a-custom-tokens (this is the part about custom tokens).

The reason why I named the Custom Token only as an "a.k.a." is because an implementing developer probably doesn't care whether the underlying method is a custom token or any other authentication override method. In fact, [since Firebase V3, the "token" is just a simple JSON string](https://github.com/kreait/firebase-php/blob/master/src/Firebase/V3/Auth/CustomToken.php#L25).

I will close this issue now, but feel free to open another one if you have any questions!
