### ISSUE TITLE
Unsubscribe a user from all topics

### ISSUE THREAD

**Issue by Lordofcodes** [kreait/firebase-php#331]
I think there is nowhere mentioned how can I unsubscribe a user from all topics.
Suppose I have subscribed a user from various topics. A, B, C , D and so on.
Now he updates his topics. Subscribed to B, D, E, F. 
I have to unsubscribes him from all the topics and subscribe to new topics.

Also, **I want to know to what topics a user has been subscribed.** 
I can know all the topics of a user but It's not in the package I make a separate API call using below url.
```
https://iid.googleapis.com/iid/info/<TOKEN>?details=true
Content-Type:application/json
Authorization:key=AIzaSyZ-1u...0GBYzPu7Udno5aA
```

**Comment by jeromegamez** [comment]
Unsubscribing an application instance from multiple/all topics is very similar to #330 - to unsubscribe them, you currently would need to loop over the subscribed topics and unsubscribe them one by one.

I'm referring to "application instance" instead of "user" because topic subscriptions are managed by instance, not by user: if I have two phones with the same app installed on both of them, there will be two independent registration tokens for both instances. You would have to subscribe phone A and B to the same topic - if you only subscribe phone A, phone B won't receive messages.

That being said, the function _is_ in the SDK, you can find its documentation at https://firebase-php.readthedocs.io/en/4.32.0/cloud-messaging.html#working-with-topic-subscriptions

```php
$appInstance = $messaging->getAppInstance('<registration token>');

$subscriptions = $appInstance->topicSubscriptions();

foreach ($subscriptions as $subscription) {
    $messaging->unsubscribeFromTopic($subscription->topic(), $subscription->registrationToken());
}
```
