### ISSUE TITLE
Auth::verifyIdToken() verifies valid tokens as revoked ( v4.32 )

### ISSUE THREAD

**Issue by krazydanny** [kreait/firebase-php#340]
The Auth::verifyIdToken() method throws an Kreait\Firebase\Exception\Auth\RevokedIdToken exception with valid idTokens generated using SOCIAL NETWORK providers on the client side and the second param (checkIfRevoked) set to true (works fine with idTokens generated from custom tokens).

**To Reproduce**

Generate an idToken with javascript, react or native SDKs and pass it to Auth::verifyIdToken( $token, true ). I've also verified the idTokens with verifyIdToken() method from the "firebase-admin" node.js package and it works ok.

I've checked the idToken

**Expected behavior**
No exception should be thrown with the checkIfExpired param set to true and using valid idTokens.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - PHP version: 7.2
 - Firebase SDK Version: 4.32

**Comment by jeromegamez** [comment]
The information that you didn‘t get an invalid token exception, but „just“ a revoked token exception let’s me think of time inconsistencies on the server (I had issues about that in the past). There‘s a third „allow time inconsistencies“ parameter to the verifyIdToken method, could you please try verifying the ID token with that enabled?

ID tokens from social auth providers are currently not directly supported by the PHP SDK - if the verification works without revocation checks, could you please share the decoded token with me so that I can help investigate what the issue might be?

**Comment by krazydanny** [comment]
I made a ver_dump() of the idToken and firebase user object and it exp, auth_time and tokensValidAfterTime attributes are correct. Also created a node.js script and used the verifyIdToken from the official Google's node.js SDK and the same token was verified successfuly :(

**Comment by jeromegamez** [comment]
I believe you, but this SDK is not as feature-rich as the official SDKs and might not work the same way as the official SDKs - in my understanding, even after a social network login, the Firebase ID token should still be just that - an ID token issued by Firebase.

The throw of a `RevokedIdToken` exception happens after the validation of the Token itself, that's why I assume that the token itself is valid.

If you call `$check = $auth->verifyIdToken($idToken)` additional parameters, you should have the token in the `$check` variable and can debug the token claims by reproducing the behavior from

https://github.com/kreait/firebase-php/blob/6bf91b0622a381ca384cddb67c4a3773f7508782/src/Firebase/Auth.php#L398-L407

For example:

```php
$check = $auth->verifyIdToken($idToken);

$tokenAuthTime = $check->getClaim('auth_time');
$uid = $check->getClaim('sub');
$user = $auth->getUser($uid);
$validSince = $user->tokensValidAfterTime;
```

And then compare the values... it has to do something with time, this is the only place where this specific exception is thrown.

I hope this helps!

**Comment by krazydanny** [comment]
Thanks! It's exactly what I've done :)

Also would be great if it can be fixed. Not supporting Social Network Provider's tokens because a line of code it's a shame :)

**Comment by jeromegamez** [comment]
If that is what you‘ve done, could you share what the actual issue is? Do the timestamps not match or do they? If you dived into the code, do you see an issue somewhere?
