### ISSUE TITLE
great package but...

### ISSUE THREAD

**Issue by tehg00se** [kreait/firebase-php#342]
This is a great package, and I was easily able to get up Laravel auth guards and integrate everything.  However, over the recent weeks trying to run after a composer update I keep getting

`/path/to/app can not be read: Cannot use SplFileObject with directories`

Exception in: /vendor/kreait/firebase-php/src/Firebase/ServiceAccount.php:174

`
> try {
>   171|             $file = new \SplFileObject($filePath);
 >  172|             $json = $file->fread($file->getSize());
 > 173|         } catch (Throwable $e) {
  >   **174|             throw new InvalidArgumentException(\sprintf('%s can not be read: %s', $filePath, $e->getMessage()));**
    175|         }
    176|
    177|         try {
    178|             $serviceAccount = self::fromJson($json);
`

I can easily go into the pacakge and modify the path obviously, but I'm just wondering what I'm doing wrong.  I have my JSON in the root of my app, and it's worked previously.  Any ideas?  Thanks guys.

**Comment by jeromegamez** [comment]
How are you using the SDK? Without a code example on how you're setting up the SDK, it's difficult to guess what might have gone wrong.

Please use the bug template (https://github.com/kreait/firebase-php/issues/new?assignees=&template=bug_report.md&title= , you can copy and paste the contents into this issue here) to provide more information.

Are you using the SDK directly or are you using the Laravel Package from https://github.com/kreait/laravel-firebase ?
