### ISSUE TITLE
Call to undefined method Kreait\Firebase\Database::getMessaging()

### ISSUE THREAD

**Issue by Waqaralipk** [kreait/firebase-php#364]
Bug:
On accessing firebase cloud component I am getting the error which is 
Call to undefined method Kreait\Firebase\Database::getMessaging()
before that, I was using createMessaging() function which is depreciated. 

-----------------------------------------------------------------------------------------------------
PHP code: (Laravel 6.0):
========================================================
$serviceAccount = ServiceAccount::fromJsonFile($serviceAccountFile);
  $factory = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->withDatabaseUri($firebaseDbUrl)
            ->create()->getDatabase();
$messaging = $factory->getMessaging();
$factory->unsubscribeFromTopic($topic, $token);
==========================================================

**Expected behavior**
It should access the cloud component but unfortunately, it doesn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/39183708/70701690-9ec92d00-1cee-11ea-9e91-76a163e3dbf9.png)

**Environment **
 - OS: [Ubuntu 18.04, ...]
 - PHP version: [7.1]
 - Firebase SDK Version: [4.368]

I am trying to install 4.8.0 version explicitly but it is installing 4.36
don't know why?
also, Can I ask you to give me a favor? 
Please update the Documentation it was some depreciated function there.

**Comment by jeromegamez** [comment]
Could you please make sure that the code examples are properly formatted? It's difficult to read, especially on mobile devices (I'm on the road right now) 😅 

There's a Laravel 6 compatible bundle at [github.com/kreait/laravel-firebase](https://github.com/kreait/laravel-firebase) that I recommend using. With its configuration, you can use Dependency Injection or Facades to access the single components.

In your issue, you write that you are accessing `Database::getMessaging()` - the Database class doesn't have this method.

`self::firebaseConnect()` is a custom method of yours, perhaps you can find something in there.

If you want to explicitly install release 4.8.0, add `"kreait/firebase": "4.8.0"` to your composer.json - although I don't see a reason why you should stick with such an old version - any newer 4.x release is fully backward compatible.

The documentation only refers to non-deprecated methods - if you're using a deprecated method, your IDE is capable to show the recommended replacement. If it doesn't please let me know where so that I can add it.

Deprecation warnings are no errors - you can still use deprecated methods without issues, they only warn you that this method/class will not exist anymore in a future 5.x release.

**Comment by jeromegamez** [comment]
I just was able to understand what you wrote in the code: `$factory->create()` returns an instance of the `Firebase` class, `$factory->create()->getDatabase()` returns a `Database` object. You‘re probably set when you remove the `->getDatabase()` part.

**Comment by Waqaralipk** [comment]
> I just was able to understand what you wrote in the code: `$factory->create()` returns an instance of the `Firebase` class, `$factory->create()->getDatabase()` returns a `Database` object. You‘re probably set when you remove the `->getDatabase()` part.

@jeromegamez  Thanks a lot. It is working now

**Comment by aloncarmel** [comment]
Just making sure everybody sees this with v5.x of the library:


require __DIR__ . '/vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;

$factory = (new Factory)->withServiceAccount(__DIR__.'/YOURKEY.json');

$messaging = $factory->**createMessaging**();

Its create messaging not getMessaging

**Comment by jeromegamez** [comment]
Thanks @aloncarmel! This is also mentioned in the troubleshooting docs: https://firebase-php.readthedocs.io/en/5.11.0/troubleshooting.html#call-to-private-undefined-method

I'll create a new GitHub issue label so that it's easier to see if an issue is related to a 4.x, 5.x or future release. 🤞

**Comment by aloncarmel** [comment]
> Thanks @aloncarmel! This is also mentioned in the troubleshooting docs: https://firebase-php.readthedocs.io/en/5.11.0/troubleshooting.html#call-to-private-undefined-method
> 
> 
> 
> I'll create a new GitHub issue label so that it's easier to see if an issue is related to a 4.x, 5.x or future release. 🤞 

Thanks! I think it's worth noting that the naming changed also. After a lot of searching I discovered that it's createm... and not getm... it's not mentioned anywhere. Thanks for this.

**Comment by SergioRe** [comment]
Solution: https://github.com/kreait/firebase-php/issues/641
