### ISSUE TITLE
ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by go24dev** [kreait/firebase-php#365]
**Describe the bug**
```
 Array to string conversion {"userId":42,"exception":"[object] (ErrorException(code: 0): Array to vendor/kreait/firebase-php/src/Firebase/Messaging/MessageData.php:23)"}
```
**To Reproduce**

```php
$message = CloudMessage::fromArray([
                'topic' => 'appEvent'
                'data' => [
                    'event' => 'servicesAreUpdated',
                    'data'  => [
                        'id'   => $service->id,
                        'name' => [
                            'EN' => $service->name,
                        ],
                        'icon' => $service->icon
                    ]
                ],
            ]);

            \FirebaseMessaging::send($message);
```

**Expected behavior**
It used to works well, but after I updated the packages I got above problem.

**Environment (please complete the following information):**
 - OS:  MacOS 10.14, Ubuntu 18.04
 - PHP version: 7.1
 - Firebase SDK Version: 4.37.0

**Comment by jeromegamez** [comment]
Are you sure this worked before? The last change concerning this was introduced with https://github.com/kreait/firebase-php/commit/c8dfdcd75a5a61cf419a62bed2ba55c7c3d2c0aa, but the code example you showed would have thrown an error before the change as well 🤔. From which version have you updated from?

The SDK currently doesn't support multi-dimensional data in the `data` field, because I understood the respective section [in the reference](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) as if the `data` field should be a one-dimensional list of key/value pairs as strings.

If you're sure this worked before or that Firebase supports multi-dimensional data payloads, I will try to confirm this and remove the constraint in the SDK.

**Comment by elexl** [comment]
Tried sending multi-dimensional data to API, but got an error. Working around by storing the data as JSON string value and decoding on client.

**Comment by jeromegamez** [comment]
@go24dev I just tested the functionality with a multidimensional array - when I remove the check in the SDK and let the multidimensional array go to the Firebase API, the API returns an error like `Invalid JSON payload received. Unknown name "key_xxx" at 'message.data[3].value': Cannot find field.`

So I will keep it as it is. If you're convinced that the Firebase APIs support this, please provide me with a reproducible code example 🙏

**Comment by jeromegamez** [comment]
Beginning with [4.38](https://github.com/kreait/firebase-php/releases/tag/4.38.0), an `InvalidArgumentException` will be thrown when the given data is not a one-dimensional array with string(able) values. This should make the issue a little more transparent.
