### ISSUE TITLE
Removing leeway configuration to avoid waiting

### ISSUE THREAD

**Issue by tnageleweb** [kreait/firebase-php#377]
Hi,
Thanks for sharing a such great work.

My question is regrinding using leewayInSeconds, the default is 5min. Once revoked (i.e.: during password update), a user need to wait 5min before he can contact my server with valid token. Is there a security reason behind this?

Is it ok to remove the following line?(in file: Firebase/Auth.php)
 $tokenAuthenticatedAt = $tokenAuthenticatedAt->modify('-'.$leewayInSeconds.' seconds');

After removing, it works as expected.

**Comment by jeromegamez** [comment]
Good catch! I think the way to go would be to apply the leeway to the `$validSince` value as well instead of removing the line, but that’s just an implementation detail - you have found a bug that must have been there since quite some time now... are you the first person to actually use the revocation check? 😂

I’ll confirm this once I’m back on a computer and fix it - expect a new release in the coming days. 
Thank you!

**Comment by tngl-fb** [comment]
Awesome. Thanks for clarification and support.

**Comment by jeromegamez** [comment]
@tnageleweb If possible, could you test #378 to make sure that this solves the problem? If it doesn't please let me know on #378 so that we can find a solution together 🙏. Thank you!

**Comment by tnageleweb** [comment]
Really sorry for the delay, @jeromegamez. For some reason notifications stopped in my device. 

Sure I will test and let you know, it is a great pleasure working with you. Thank you.

**Comment by jeromegamez** [comment]
Resolved with #378, merged with 6c090e9813cb38ce86e3fe6d42060da22fb2b3c4 and 5f6096a66c2b9242530cb82054259528adb0efc6 🎉
