### ISSUE TITLE
Multicast and unexisting/expired tokens

### ISSUE THREAD

**Issue by ck84** [kreait/firebase-php#396]
**Describe the bug**
We are using the libraries multicast capabilities to sent messages to the devices of a user (a user can have multiple devices, therefor we track multiple device tokens for each user). In an older version of the library it was possible to send single messages to a single device token. With the single message it was possible to identify if the device for a registration token was unregistered or if the message was delivered successfully.
With the multicast implementation all messages are reported as successfully delivered - even for registration tokens which are unregistered. It seems that the subResponses are different depending on the registered / unregistered state of the device / deviceToken.

registered device:
`{
  "name": "projects/[project-name]/messages/1584562990026860"
}`

probably unregistered device
`{
  "name": "projects/[project-name]/messages/0:1584562990029639%3f04f5553f04f555"
}`

Are we missing something or is this the intended behavior?

**To Reproduce**
item 0 = successfully delivered
item 1 = old unregistered token

```php
$report = {Kreait\Firebase\Messaging\MulticastSendReport} [1]
 items = {array} [24]
  0 = {Kreait\Firebase\Messaging\SendReport} [3]
   target = {Kreait\Firebase\Messaging\MessageTarget} [2]
   result = {array} [1]
    name = "projects/[project-name]/messages/1584566014466720"
   error = null
  1 = {Kreait\Firebase\Messaging\SendReport} [3]
   target = {Kreait\Firebase\Messaging\MessageTarget} [2]
   result = {array} [1]
    name = "projects/[project-name]/messages/0:1584566014634780%3f04f5553f04f555"
   error = null
```

**Expected behavior**
It should be possible to differentiate between successfully sent messages and messages that couldn't be sent because the device got unregistered when using multicastmessage

**Environment (please complete the following information):**
 - OS: webdevops/php-nginx-dev:7.2 (debian based docker-image)
 - PHP version: 7.2.26
 - Firebase SDK Version: 4.36.2

**Comment by jeromegamez** [comment]
At the moment, the SDK is not able to handle expired tokens, but if the `0:` prefix is an indicator for an expired token, I can make it happen.

The issue is that Firebase still accepts messages to be sent to those tokens - if a device has been unregistered from the project, it will return a failure status with `NOT_FOUND`/ÙNREGISTERED` as the detail. So, from an SDK point of view, it's not a failure, as Firebase has accepted the message. 🤔

**Comment by ck84** [comment]
Hello,
thank you for the explanation.
Is the `0:` just an indicator or is it bulletproof to check for this prefix to remove the devices?

Kind regards

**Comment by jeromegamez** [comment]
To be honest, I don't know - it's only the only difference I've seen between the two results, I don't even know **if** it is an indicator at all 🤔

**Comment by tobischulz** [comment]
Maybe i'm wrong but i guess on the legacy api for firebase (fcm) there was a response with an array of expired tokens. This would be awesome if there is a way to have any functionality cause we got the same usecase to send to multiple devices for a user. 

So a cleanup would be very nice. If its not accessible by the firebase api response, maybe there is a job that can request expired tokens from firebase to clean up the users tokens database?

**Comment by jeromegamez** [comment]
What do you mean by „cleanup“? 😅

Unfortunately, I don‘t have enough test devices (actually: none 😅) to confirm that a `0:` prefix in the returned message ids indicates an expired device token - if one of you can reliably confirm this, I‘ll be happy to implement an according check.

This SDK doesn‘t communicate with the legacy API because the payloads are very different, but if you can provide me with any endpoint to retrieve expired device tokens, let me know and I‘ll make it work. 💪

Lastly: the OP mentioned „possibly expired tokens“ - my current knowledge is: an expired token is no different to a token that wasn‘t registered with the project in the first place - both would be reported in the MulticastSendReport as a delivery failure. So, at this point in time, I‘d say: if a token ist not reported as „Not found“, then it isn‘t expired - but I‘d love to be proven wrong 😅

**Comment by tobischulz** [comment]
Im getting many of the Kreait\\Firebase\\Exception\\Messaging\\NotFound Exceptions with the message "Requested entity was not found.".

So i guess its caused by expired tokens or something? So i would like to have a way to fix that cause my logfiles are filled with that exceptions.

**Comment by jeromegamez** [comment]
In a way, that's good! Depending on how you send messages, you could resolve this ad-hoc like this:

### When sending a message to a single device

```php
$message = CloudMessage::withTarget('token', $token = 'xxx')
	->withNotification(/* ... */)
    // etc.
; 

try {
    $messaging->send($message);
} catch (\Kreait\Firebase\Exception\Messaging\NotFound $e) {
	// Delete $token from local token storage
}
```

### When sending multicast messages

```php
$message = CloudMessage::new()
	->withNotification(/* ... */)
    // etc.
;

$report = $messaging->sendMulticast($message, $tokens);

foreach ($report->failures() as $failure) {
    /** @var SendReport $failure */
    if ($failure->messageWasSentToUnknownToken()) {
        $token = $failure->target()->value();
	    // Delete $token from local token storage
    }
}
```

**Comment by ck84** [comment]
That was exactly the solution which we had implemented in our API and it worked for single messages until a certain version of this library. Maybe there was also something changed regarding the handling of tokens on the Firebase side?
For Multicast we also expected to find the expired tokens in the array of failures which wasn't the case. Instead they were found in the list of succeses.

In our tests the leading `0:` was only added to old tokens(which we grapped from the database) or when we reinstalled the mobile app on a devices and a new token was created for this device(and tested the push stuff with the old token for this device). But this was just a try and error approach and we are not sure if this is correct ...

**Comment by jeromegamez** [comment]
If you go back to the old version of the SDK that still worked, does it then work again? That would make me sad because I put much effort into not breaking things, but would still be good news because then I could investigate what I changed that broke it.

The problem for me are the mixed signals here (not your fault, of course!) - on the one hand, the amount of `NotFound` exceptions grows larger, on the other hand, the exceptions are not triggered anymore. I honestly don't know how I should proceed here - in my manual tests (with browser apps, not mobile devices), I always get the exceptions when a device token gets refreshed

**Comment by tobischulz** [comment]
Sorry if i added more confusion to this conversation. Thanks for your example. I will try that and report if that worked to deleted "old" tokens.

Thank you

**Comment by tobischulz** [comment]
This works for me. Thank you for your help. Will hit the sponsor button. This package helps me a lot.

```php
if ($report->hasFailures()) {
    foreach ($report->failures()->getItems() as $failure) {
        /** @var SendReport $failure */
        if ($failure->messageWasSentToUnknownToken()) {
            $token = $failure->target()->value();

            PushToken::where('token', $token)
                ->delete();
        }
    }
}
```

**Comment by ck84** [comment]
Sorry I haven't had the time yet to look into it again - I plan to do this in a staged project to ensure no side-effects influence the outcome.

This does also work in our project. Nevertheless the issue we observed was that messages that were sent to devices which should be unregistered were listed in the array of the succcessful send-reports.

**Comment by jeromegamez** [comment]
@tobischulz There's a helper that I've apparently forgotten about: [`MultiCastSendReport::unknownTokens()`](https://github.com/kreait/firebase-php/blob/master/src/Firebase/Messaging/MulticastSendReport.php#L148)

This would enable you to do

```php
foreach ($report->unknownTokens() as $token) {
	PushToken::where('token', $token)->delete();
}
```

without needing to check for failures yourself 🤞

**Comment by tmblog** [comment]
Hi, how can I get the token that failed using multicast:

```
foreach ($report->failures() as $failure) {
    /** @var SendReport $failure */
    if ($failure->messageWasSentToUnknownToken()) {
        $token = $failure->target()->value();
	    // Delete $token from local token storage
    }
} 
```
I assumed `$token` would be the token but printing it doesn't give anything.
I would then delete it from the database I have it stored in.

Thank you

**Comment by jeromegamez** [comment]
@tmblog It indeed should be the token. What does "printing" mean in your context, would you mind sharing the actual code that you use? What does `$failure->target()->type()` return? Unless the multicast response from the Firebase APIs has changed (which should have been discovered by the test suites), it's almost impossible that a message target has no value. (But I'd love to be wrong about that, because then I can fix it :))

**Comment by tmblog** [comment]
@jeromegamez thanks for getting back.
If I `echo` or `print_r` either `$failure->target()->type()` or `$failure->target()->value()` there is nothing shown.

I have run this:
```
echo 'Successful sends: '.$report->successes()->count().PHP_EOL;
echo 'Failed sends: '.$report->failures()->count().PHP_EOL;

if ($report->hasFailures()) {
    foreach ($report->failures()->getItems() as $failure) {
        echo $failure->error()->getMessage().PHP_EOL;
    }
}
```

And the output is: 
`Successful sends: 0 Failed sends: 1 Requested entity was not found.`
I did a print_r on $failure and I could see the token in the returned object but as private. Here's part of the returned object:

`Kreait\Firebase\Messaging\SendReport Object ( [target:Kreait\Firebase\Messaging\SendReport:private] => Kreait\Firebase\Messaging\MessageTarget Object ( [type:Kreait\Firebase\Messaging\MessageTarget:private] => token [value:Kreait\Firebase\Messaging\MessageTarget:private] => fQUnD6V9R1eIDK....`

Is there a method to access that token just like the ` [message:protected] => Requested entity was not found. ` via `$failure->error()->getMessage()`?
Thanks
