### ISSUE TITLE
Should putenv('GOOGLE_APPLICATION_CRED=./file.json') work?

### ISSUE THREAD

**Issue by markkimsal** [kreait/firebase-php#397]
**Describe the bug**
The code in in `ServiceAccount/Discovery/FromEnvironmentVariable.php` seems to want to work with paths to files, but it doesn't.

```php
    public function __invoke(): ServiceAccount
    {
        $msg = \sprintf('%s: The environment variable "%s"', static::class, $this->name);

        if (!($path = $this->getValueFromEnvironment($this->name))) {
            throw new ServiceAccountDiscoveryFailed(\sprintf('%s is not set.', $msg));
        }

        if (\mb_strpos($path, '{') === 0) {
            $msg .= 'is a JSON string';
        } else {
            $msg .= \sprintf(' points to "%s"', $path);
        }

        try {
            return ServiceAccount::fromValue($path);
        } catch (Throwable $e) {
            throw new ServiceAccountDiscoveryFailed(
                \sprintf('%s, but has errors: %s', $msg, $e->getMessage())
            );
        }

```

Why is the variable called "$path"?  Why does it check if it starts with '{' or not?

ServiceAccount::fromValue($path) definitely doesn't work with a file path.

**Comment by jeromegamez** [comment]
It's a check that `ServiceAccount::fromValue()` does as well, but pre-emptively to provide a more meaningful error message if something fails.

`FromEnvironmentVariable` was only able to work with paths in an earlier version, that's why the variable (still) called `$path` (in the meantime, it has gained the ability to process a full JSON key in the environment variable).

I'm fairly confident that `ServiceAccount::fromValue()` *does* work 😅 - you wrote in the title that you used `GOOGLE_APPLICATION_CRED` as the environment variable - supported environment variable names are `GOOGLE_APPLICATION_CREDENTIALS` and `FIREBASE_CREDENTIALS`, could that be the issue?

**Comment by markkimsal** [comment]
CRED was shortened for the title only.  I had this working by specifying the file, but it has since stopped working.  Currently on 4.40.1  I'm not 100% certain it worked before, but fairly certain that I wasn't getting these errors and was pushing info into firebase with unit tests.

Just to reiterate, I'm not getting a clear yes or no to the following question: should the environment variable be allowed to point to the location of a json file similarly to how Google's firebase documentation describes?

**Comment by jeromegamez** [comment]
Yes it should work. 

Please try removing the `./` from the beginning of the string if you‘re invoking the call from the same directory as the location of your credentials file, or use a full path, the path is resolved at runtime

**Comment by markkimsal** [comment]
Indeed it works if you put in a full path or "../config/firebase.credentials.json" because the laravel process has a CWD of "public/"

Thanks for the clarification.

For anyone else stumbling upon this issue, use `base_path()` to wrap your file path:

```php
//some application file
putenv('GOOGLE_APPLICATION_CREDENTIALS='. base_path(config('firebase.credentials.file'))); 

//config/firebase.php
return [
    'credentials' => [
        'file' => 'config/firebase_credentials.json',   //or storage/app/firebase_credentials.json
    ],
];
```
