### ISSUE TITLE
Application default credentials don't work

### ISSUE THREAD

**Issue by constantijn** [kreait/firebase-php#399]
Hi,

I was looking around the service account discovery file and i saw these methods were used to discover them:

```
    public function getDefaultMethods(): array
    {
        return [
            new Discovery\FromEnvironmentVariable('FIREBASE_CREDENTIALS'),
            new Discovery\FromEnvironmentVariable(CredentialsLoader::ENV_VAR),
            new Discovery\FromGoogleWellKnownFile(),
            new Discovery\OnGoogleCloudPlatform(),
        ];
    }
```

The FromGoogleWellKnownFile one seems to imply that it will look for the application default credentials in `$HOME/.config/gcloud/application_default_credentials.json`. That file exists on my system. However if i don't set GOOGLE_APPLICATION_CREDENTIALS php errors out with 

```
Kreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"FIREBASE_CREDENTIALS\" is not set.\nKreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"GOOGLE_APPLICATION_CREDENTIALS\" is not set.\nThe following fields are missing/empty in the Service Account specification: \"project_id\", \"client_email\", \"private_key\". Please make sure you download the Service Account JSON file from the Service Accounts tab in the Firebase Console, as shown in the documentation on https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app\ncURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)",
```
Can you fix it so that the application default credentials get picked up properly?

**Comment by jeromegamez** [comment]
I moved this into the main repository because it's not directly related to the Laravel package.

Please try running https://github.com/jeromegamez/firebase-user-credentials-test on your machine with your user refresh credentials (you'll have to update the project ID in `script.php`). If no service account is explicitly given, it will use the application default credentials in ~/.config/gcloud

For me (owner of the project) it was not possible to perform any actions on my project except accessing the realtime database.

If it works for you, please let me know how you did it ^^ - if you have ideas to make it work, please let me know as well!

For the moment, I'm putting this endeavor on hold - Google advertises using service accounts for authentication (in the Admin context) everywhere they can, and I'm not sure it's worth the effort if I cannot ensure that everything works when using non-service account credentials :/

**Comment by constantijn** [comment]
Verifying JWTs works without a service account, but listing users doesn't seem to work.
Ok, back to the drawing board and time to go dust off service accounts i guess. :\

**Comment by constantijn** [comment]
I do appreciate the effort btw!

**Comment by jeromegamez** [comment]
I‘m currently working on integrating the changes of this POC-branch into the main branch and to make the SDK as independent from an actual Service Account as possible.

I‘m currently in a state where it is possible to at least instantiate all components without triggering the Google Warnings, in a way that will only trigger (hopefully with descriptive enough) errors if it‘s not possible to use a given component...

May I ping you again when I‘m satisfied enough with the progress so that you could have another look at it? 🙈

**Comment by constantijn** [comment]
Sure!
It would really help to not need a service account to do JWT validations. I have some services that only need to validate google's JWTs, but need a service account anyway. It doesn't really use the service account, but it needs it to not crash.
