### ISSUE TITLE
withVerifierCache must implement Psr\SimpleCache\CacheInterface

### ISSUE THREAD

**Issue by thomasweisend** [kreait/firebase-php#416]
I'm attempting to use the FilesystemAdapter component from Symfony to cache verified token requests however I'm getting the error `":withVerifierCache() must implement interface Psr\SimpleCache\CacheInterface"` I'm not completely sure that the FilesystemAdapter does in fact implement the interface. Am I doing something wrong here? When I used your other library "firebase-tokens", this cache worked correctly. I switched over to this library because it seemed as though there was more support.

**Comment by jeromegamez** [comment]
Would https://symfony.com/doc/current/components/cache/psr6_psr16_adapters.html perhaps help with that?

If you‘re switching to the SDK only because of the perceived more extensive support, please be assured that the tokens library (which is used here as well) receives the same amount of support, it just doesn‘t need as much 😅

**Comment by jeromegamez** [comment]
As this issue seems to have occurred while using the [Symfony Bundle for the SDK](https://github.com/kreait/firebase-bundle) I'm glad to be able to say that this issue is resolved since [Release 2.10](https://github.com/kreait/firebase-bundle/releases/tag/2.1.0) of the bundle. Please update and let me know if it works for you.
