### ISSUE TITLE
Can't connect to firebase

### ISSUE THREAD

**Issue by vitalijalbu** [kreait/firebase-php#417]
Can't connect to firebase, I'd like to get json database data.
<img width="1653" alt="Schermata 2020-04-28 alle 15 57 56" src="https://user-images.githubusercontent.com/40239902/80496693-db2dba80-8969-11ea-9adb-a9804827563d.png">
<img width="769" alt="Schermata 2020-04-28 alle 16 04 13" src="https://user-images.githubusercontent.com/40239902/80496755-e8e34000-8969-11ea-8912-987d178c2f4d.png">

**Comment by jeromegamez** [comment]
You give me a lot of guesswork to do.

I can already tell that you have followed an external tutorial because you are using methods that have been deprecated for a very long time.

You seem to be using a 4.x release, so please follow the documentation at https://firebase-php.readthedocs.io/en/4.44.0/overview.html

https://firebase-php.readthedocs.io/en/4.44.0/realtime-database.html shows you how to actually connect to the Realtime Database (in your code, you're only getting the Database component without actually doing anything with it).

If you have found a bug, please create a new issue, use the provided issue template, and please don't provide just a big screenshot 😅
