### ISSUE TITLE
Should *Attributes methods more accurately be referred to as *Claims?

### ISSUE THREAD

**Issue by sdwru** [kreait/firebase-php#427]
Unless I am mistaken, the feature that firebase-php sdk refers to as custom attributes is the same feature that Firebase and JWT refers to as custom claims.

It can be confusing and firebase-php sdk should be using the standardized terminology for the method names and documentation imo.

https://firebase-php.readthedocs.io/en/5.3.0/user-management.html?highlight=setCustomUserAttributes#update-a-user

https://auth0.com/docs/tokens/concepts/jwt-claims#custom-claims

https://firebase.google.com/docs/auth/admin/custom-claims

https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

**Comment by jeromegamez** [comment]
The attributes you’re referring to are part of the user records stored in the auth database.

JWT claims are part of the custom JWT token creation used here https://firebase-php.readthedocs.io/en/5.3.0/authentication.html

**Comment by sdwru** [comment]
Perhaps I am confused.  Yes it is part of the ID token but I am not referring to custom tokens.  

I am referring to what JWT and Firebase call "custom claims" which firebase-php calls custom attributes.   In the ID token, not the custom token.

https://github.com/kreait/firebase-php/blob/64b383c5bd253cd3927821d8cf891a2e76e7e88e/tests/Unit/Request/UpdateUserTest.php#L145

**Comment by jeromegamez** [comment]
These are two separate concerns. The first method you‘re using is a user record/profile updates as described at https://firebase.google.com/docs/reference/rest/auth#section-update-profile - unfortunately the docs don‘t show anymore that you are/were able to update much more than currently described there.

The Firebase auth api seems to return user attributes as JWT claims, but still user properties != JWT claims. 

From another perspective: the `setCustomUserAttributes` is not JWT-related, it‘s user-profile related. Only the `createCustomToken` and `verifyIdToken` methods work with JWT directly.

The custom user attribute and UserRecord stuff is located in the Auth component (suggesting that they have something to do with authentication itself) because everything user related is in the Auth scope (in the official SDKs as well).

**Comment by sdwru** [comment]
Let me try simplify it further.  If we were using Python instead of PHP we would use the official Firebase Python SDK instead of firebase-php SDK.

https://firebase.google.com/docs/auth/admin/custom-claims#python_2

The function that firebase-php calls `setUserCustomAttributes()`

Google firebase official Python SDK calls `setCustomUserClaims()`
https://firebase.google.com/docs/auth/admin/custom-claims#backend_implementation_admin_sdk

**Comment by jeromegamez** [comment]
Thank you for simplifying it for me. Since the beginning of the SDK I tried to be as close to the official SDKs as possible, so I do believe the method name was accurate at least until some point in the past. It also wasn‘t always the case that the custom user attributes resulted in custom claims - they originally were only used in custom authentication tokens. 

Thanks for making me aware of this, I‘ll add the renamed method and deprecate the old one.

**Comment by jeromegamez** [comment]
Implemented with https://github.com/kreait/firebase-php/commit/04daec51e373f93633331f1046713c5126583483

**Comment by chyt** [comment]
In https://github.com/kreait/firebase-php/commit/04daec51e373f93633331f1046713c5126583483#diff-7bdefa15084e02ff18467cb1d8e06f77R67 shouldn't the URI just be `update` instead of `https://identitytoolkit.googleapis.com/v1/accounts:update` as is consistent with the rest of the client?

**Comment by jeromegamez** [comment]
@chyt Firebase has started now and then changing some of the endpoints and payloads since the SDK methods have been created - both the old and new ones still work, but when I'm working at a component/method, look up the endpoints and notice I change, I adapt it here in the SDK. It's inconsistent throughout the code, but as long as it still works (ensured by the integration tests), it shouldn't really matter (except if you've found an error, of course!). Another reason why I started changing relative paths to full URIs is that I want(ed) to get rid of the `base_uri` configuration in the factory. When I started the SDK, most API endpoints were served by a single URI; nowadays functionality is distributed through different APIs which make the base URIs in the API clients more difficult to handle.

I can imagine that this is not a satisfying answer, but I don't have another one 😅
