### ISSUE TITLE
Retrieving HTML from Firepad

### ISSUE THREAD

**Issue by SantiGodoy** [kreait/firebase-php#432]
Sorry if this is not the best place to ask this question but i'm desperate at this point.

Is there a way to get the HTML code from a Firepad document in order to have this content in my PHP code to store it in my own database?

Firepad already has a getHtml() method but i can't extract it from a javascript file to my PHP code where i want to have it.

I don't know how to make up the document from the history structure in the Firebase database. I don't find how Firepad get the document each time by looking at the code because there is no text field or something like that in the database to get it so there must be a way to do this.

Thank you!

**Comment by jeromegamez** [comment]
I‘m not sure if this is the right place because I don‘t know what „Firepad“ is, and what you mean with „HTML Code“ and „History structure“.

If you want to access a Firebase project with PHP, this SDK can provide that, but you should familiarize yourself with what Firebase is and what it can do, and with the documentation of this SDK.

If you get stuck with something concerning this SDK, feel free to join the Discord Server mentioned in the readme, that‘s more interactive than a Github Issue 🤞
