### ISSUE TITLE
Send multicast cloud message receive nothing on device if device list has mismatch registration ids

### ISSUE THREAD

**Issue by hyquoccuong** [kreait/firebase-php#450]
I'm using this sdk for send notification from my server to devices, and catch a problem with function sendMulticast of CloudMessaging

For some reasons, in my database, I stored some mismatch device registration ID so when I send message by sdk it responses:

Successful sends: 3
Failed sends: 5
Requested entity was not found.
Requested entity was not found.
Requested entity was not found.
Requested entity was not found.
Requested entity was not found.

The problem is with my 3 devices with correct registration ids stored, only first device (first in the list) receive notification, 2 other devices (at last in the list) recevie nothing, I think firebase stop send message after catch mismatch registation Id

Environment

OS: Centos 7.4
PHP version: 7.0.13
Firebase SDK Version: 4.44.0

Could you please check what cause problem with send multicast feature? Is it firabase's problem or sdk's problem?

**Comment by jeromegamez** [comment]
Unfortunately, there is nothing we can do from the SDK side of things. The 8 tokens have been successfully sent from your server to the Firebase API, and Firebase confirms this by giving back a status for all 8 of them (5 were not found, 3 have been accepted). The delivery to the end-user devices is asynchronous, and we have to rely on Firebase to deliver them.

In summary: as long as Firebase accepts a cloud messaging request, we have to assume that the SDK did its job.

(I would prefer if this was a bug in the SDK, because then there would be something to fix 😅)

**Comment by hyquoccuong** [comment]
Yeah I also think it's their API problem, but I hope someone here got same problem can give us a solution to fix that :(
