### ISSUE TITLE
what does ('/path/to/firebase_credentials.json'); look like?? How do I make it?

### ISSUE THREAD

**Issue by Coners** [kreait/firebase-php#463]
I am going to leave these both here 'cause this has genuinely stumped me,

Question 1)

 I have a "fire base web app" and it comes with lots of javascript. I am assuming I can simply get the details to make a `/path/to/firebase_credentials.json` here it is 

![image](https://user-images.githubusercontent.com/49714898/90502148-4c75c100-e145-11ea-8617-cc4ee92b187b.png)

my question is how do I make a `/path/to/firebase_credentials.json`  [as needed here](https://firebase-php.readthedocs.io/en/stable/setup.html#google-service-account) from this sort of thing

**NOTE: that if I simply curl I can EASILY do this, with an API key and a token or topic, but I do not want to curl, i'd like to use your library**

Question 2) 

Your documentation also contradicts this assumption that I made. Despite being able to use assumption 1 to do ios, android and javascript. It states [here](https://firebase-php.readthedocs.io/en/stable/setup.html#google-service-account)  that I need to go to https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app and then `kreait/firebase-php` will need me to give `kreait/firebase-php` factory a `/path/to/firebase_credentials.json` the problem is that NONE of the samples available are anything like json nor php, they are 'nodejs','Java','Python','Go','C#' so obviously I have to "build" my own format. But who knows what that is? I don't, because I am not a mind reader and there is no example.

**YOU DO NOT DECLARE THAT FORMAT IN YOUR DOCUMENTATION ? WHY NOT?**

**GOOGLE DO NOT PROVIDE .json AS A OPTION**

**Comment by Coners** [comment]
I think I figured it out  .. I needed to go here https://console.firebase.google.com/project/_/settings/serviceaccounts/adminsdk and then click the link as shown.. is this correct?

![image](https://user-images.githubusercontent.com/49714898/90503697-c73fdb80-e147-11ea-8621-a5d761d0fe3d.png)

**Comment by jeromegamez** [comment]
The documentation exists to avoid making false assumptions 😅 . `kreait/firebase-php` is an Admin SDK and has to be set up differently, with a Service Account instead of an API Key, because it provides full admin permissions on your whole Firebase project.

https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app does in fact contain the following passage:

![image](https://user-images.githubusercontent.com/67554/90503286-70d69b00-e14f-11ea-84db-32e3e5d1531a.png)

I haven't copied those instructions into my docs because I didn't want them to be outdated in case Google changes the process in the future. But I will change it to link to https://firebase.google.com/docs/admin/setup#initialize-sdk directly, to make things a little easier.

**Comment by jeromegamez** [comment]
Please keep in mind that this is an unofficial Admin SDK, that's why you won't find PHP-specific instructions in the official docs.

**Comment by Coners** [comment]
> Please keep in mind that this is an unofficial Admin SDK, that's why you won't find PHP-specific instructions in the official docs.

I know but I think you need to write "WE DO NOT USE THE API KEY, yuo won't be able to add a web app and use the api key from there, WE RELY ON THE ROOT LEVEL JSON AND you'l know when you see it cos IT LOOKS LIKE THIS (fuzzed out) (AND THEN add THE LINK that I gave not just the one you gave with a picture) and say "we call it `firebase_credentials.json`" but google cal it "generate new private key"

**Comment by jeromegamez** [comment]
If you read through https://firebase.google.com/docs/admin/setup, you will only find instructions _what_ to do, and not what _not_ to do, and that's how documentation generally is structured (at least in my experience).

That's why you won't find a "do not use the API key" sentence in the official docs as well, just the section 

> If you are interested in using the Node.js SDK as a client for end-user access (for example, in a Node.js desktop or IoT application), as opposed to admin access from a privileged environment (like a server), you should instead follow the instructions for setting up the client JavaScript SDK.

You can find the same text here https://firebase-php.readthedocs.io/en/stable/index.html (and it's even highlighted)

You will also not find a "this is how a service account file looks like" section in the official docs because you don't need to know how it looks like if you follow the steps.

I agree that the documentation could be clearer (in fact I will copy the steps from the official documentation to mine to improve it), but I disagree with your approach of assuming something although it's documented otherwise and then shouting at an open-source project maintainer for not meeting them 🤷‍♂️.

**Comment by jeromegamez** [comment]
Although this is now closed, feel free to add further comments if you wish.

**Comment by Coners** [comment]
`If you read through https://firebase.google.com/docs/admin/setup, you will only find instructions what to do, and not what not to do, and that's how documentation generally is structured (at least in my experience).`

3 hours of my time disagrees

 - ios - 20 minutes
 - android - 20 minutes
 - PHP via curl 20 mins
 - PHP with your instructions 3 hours..
