### ISSUE TITLE
Client error: `POST https://fcm.googleapis.com/fcm/send` resulted in a `401 INVALID_KEY` response

### ISSUE THREAD

**Issue by AkshayRSI** [kreait/firebase-php#465]
**Describe the bug**
I am using Laravel FCM (Firebase Cloud Messaging) Notification Channel for creating notification. I am getting below error
Client error: `POST https://fcm.googleapis.com/fcm/send` resulted in a `401 INVALID_KEY` response

```php
// Code to reproduce the behavior
class DemoNotification extends Notification
{

    public function via($notifiable)
    {   
        return ['fcm'];
    }

    public function toFcm($notifiable) 
    {
        $message = new FcmMessage();
        $message->setHeaders([
            'project_id'    =>  "478830046316"   // FCM sender_id
        ])->content([
            'title'        => 'Foo', 
            'body'         => 'Bar', 
            'sound'        => '', // Optional 
            'icon'         => '', // Optional
            'click_action' => '' // Optional
        ])->data([
            'param1' => 'baz' // Optional
        ])->priority(FcmMessage::PRIORITY_HIGH); // Optional - Default is 'normal'.
        
        return $message;
    }
}

**Comment by jeromegamez** [comment]
As this is handled by the FCM Notification Channel package, please ask your question in the GitHub repo of the package at https://github.com/laravel-notification-channels/fcm

Unfortunately, I don't know the package well enough to be able to help, and I believe the issue is not located in the SDK itself. (Feel free to add further comments if you think that it actually is 😅)
