### ISSUE TITLE
Fatal error lcobucci/JWT

### ISSUE THREAD

**Issue by mikiamomik** [kreait/firebase-php#541]
Hi,
I use this library in a wp plugin.
I call it from composer like this
```
{
  "name": "mp/my_plugin",
  "description": "My plugin",
  "license": "MIT",
  "type": "wordpress-plugin",
  "authors": [
    {
      "name": "Mirko Picaro",
    }
  ],
  "repositories": [],
  "require": {
    "php": ">=5.4.0",
    "kreait/firebase-php": "5.11"
  }
}
```
if I choose "kreait/firebase-php" > 5.12, this error appear

```
Parse error: syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ../vendor/lcobucci/jwt/src/Configuration.php on line 22
--
```

**Comment by jeromegamez** [comment]
You have defined that PHP needs to be a version `>=5.4.0`, this includes PHP 7.4 and PHP 8.0.

The error points to this line: https://github.com/lcobucci/jwt/blob/6d8665ccd924dc076a9b65d1ea8abe21d68f6958/src/Configuration.php#L22

Named properties are only available since PHP 7.4, so I have to assume that you are using `lcobucci/jwt`4.x. You can confirm that version 4 is installed by doing a `composer show | grep lcobucci`.

The SDK supports version 3.x and 4.x of `lcobucci/jwt`, so you should able to fix this by fixing your dependencies to this version, either with a `composer require "lcobucci/jwt:^3.4.1` or by adding the line `""lcobucci/jwt": "^3.4.1" in the `require` section of your composer.json.

Don't forget to change the version constraint for the SDK from `5.11` to `^5.11` afterwards 🤞

**Comment by jeromegamez** [comment]
Please note that this SDK requires at least PHP 7.2 to work, so the PHP version constraint of `>= 5.4.0` doesn't really make sense, since you will not be able to use it on PHP 5.4, 5.5, 5.6, 7.0 and 7.1.

**Comment by mikiamomik** [comment]
i'm using PHP 7.2.34 in my server 
and PHP 7.2.33 in my local machine.

> Named properties are only available since PHP 7.4, so I have to assume that you are using lcobucci/jwt4.x. You can confirm that version 4 is installed by doing a composer show | grep lcobucci.

**YES**


> The SDK supports version 3.x and 4.x of lcobucci/jwt, so you should able to fix this by fixing your dependencies to this version, either with a composer require "lcobucci/jwt:^3.4.1 or by adding the line "lcobucci/jwt": "^3.4.1" in the require section of your composer.json.
> 
> Don't forget to change the version constraint for the SDK from 5.11 to ^5.11 afterwards

so i need to change my composer.json in

```
...
  ],
  "require": {
    "php": ">=7.2",
    "mp/wrappers": "2.*",
    "lcobucci/jwt": "^3.4.1",
    "kreait/firebase-php": "^5.14.1"
  }
```

??

**Comment by jeromegamez** [comment]
Yes 🤞

**Comment by mikiamomik** [comment]
it works!

**Comment by jeromegamez** [comment]
Very good, glad I could help! 😊
