### ISSUE TITLE
symfony directions?

### ISSUE THREAD

**Issue by ktwbc** [kreait/firebase-php#55]
The abandoned Symfony bundle points to this repo and says there should be a symfony doc at https://github.com/kreait/firebase-php/blob/master/doc/symfony.md but it's not here. Where are the migration directions?

**Comment by jeromegamez** [comment]
Hi Kris,

there are no migration instructions to go to version 2.x because it has been a rewrite from the ground up. I'll update the [link to the symfony integration document](https://github.com/kreait/firebase-php/blob/69496a13084710ff36d693439297e778dde178f0/doc/symfony.md) for version 1.x in the bundle, but as you see, it's just the standard way of defining a service in Symfony anyways.

Cheers!
