### ISSUE TITLE
Anonymous authentication with symfiny bundle

### ISSUE THREAD

**Issue by adadgio** [kreait/firebase-php#57]
How does anonymous (or any...) authentication works with the Symfony bundle ? I cant find any specific documentation for that. Would be a nice addition to the docs.

**Comment by jeromegamez** [comment]
The Symfony bundle is deprecated and unmaintained since 2015 (see https://github.com/kreait/firebase-bundle#this-project-is-abandoned-and-not-longer-maintained), I definitely would not recommend using it :)

Similar to the official admin SDKs, this one isn't meant to authenticate users directly as well. This is noted on http://firebase-php.readthedocs.io/en/latest/index.html and https://firebase.google.com/docs/admin/setup.

You can perform actions as a given user with authentication overrides, as described here: http://firebase-php.readthedocs.io/en/latest/authentication.html#authentication-overrides-a-k-a-custom-tokens - but this is an **override** from a privileged environment (your server), not authentication itself.

You might be interested in the progress of #54, though.
