### ISSUE TITLE
Uploading to Storage not working

### ISSUE THREAD

**Issue by desmeit** [kreait/firebase-php#571]
I cannot find any example how to upload a file to Firebase Storage.

I tried:

```
    $serviceAccount = ServiceAccount::fromJsonFile( XXX.json');
	

    $storage = (new Factory())
        ->withServiceAccount($serviceAccount)
        ->withDefaultStorageBucket()
        ->createStorage();
```

This is not working. Is there any example?

**Comment by jeromegamez** [comment]
As stated in the docs, the SDK provides a bridge to the official Google Cloud Storage library. You can find links to usage examples at https://firebase-php.readthedocs.io/en/5.14.1/cloud-storage.html

**Comment by desmeit** [comment]
What is meaning with "bridge"? Should I install the Google SDK as well? In the Examples I cannot find how to authenticate.

**Comment by jeromegamez** [comment]
> What is meaning with "bridge"? Should I install the Google SDK as well? In the Examples I cannot find how to authenticate.

Once you've initialized the storage as you did in the original post, you can use 

```php
$storageClient = $storage->getStorageClient();
```

to receive an authenticated storage client (= an instance of `\Google\Cloud\Storage\StorageClient`)

**Comment by desmeit** [comment]
Thank you very much. I get an error:

`Uncaught Error: Too few arguments to function Kreait\Firebase\Factory::withDefaultStorageBucket(), 0 passed in `

The docs says:

`It is not necessary to change the default storage bucket in most cases.`

Whats wrong with imy code?

**Comment by desmeit** [comment]
okay i got it, I have to take my project name. But I have another error:

`Fatal error: Uncaught Error: Call to protected method Kreait\Firebase\Factory::createStorage() `

**Comment by jeromegamez** [comment]
I believe you're using a 4.x release of the SDK instead of a current 5.x release (I can only guess since you discarded the suggestions while creating this Bug Report 🙈)

If you're on PHP 7.2 or newer, please update the SDK to a 5.x release, and then head over to https://firebase-php.readthedocs.io/en/5.14.1/troubleshooting.html#call-to-private-undefined-method

If you prefer to stay on a 4.x release, you can find it's documentation at https://firebase-php.readthedocs.io/en/4.44.0/troubleshooting.html - but I wouldn't advise it, it hasn't received updates in quite a while and has not all the features.

**Comment by desmeit** [comment]
Yes I need to stay to 4.4 because I need to use the firestore-php sdk:
https://github.com/morrislaptop/firestore-php

This is not working with newer versions. Very complicated.

**Comment by jeromegamez** [comment]
4.4 is a _really_ old version :/. The best solution really would be to install the gRPC PHP extension - that would make sure that you can make full use of Firestore with all of its features, including those of this SDK.

As an alternative, you could try to use https://github.com/ahsankhatri/firestore-php, but that library hasn't been updated for a while as well…

I'm afraid my time doesn't allow me to provide help for an unsupported SDK release here - for individual support, you could become a sponsor to gain access to a sponsors-only Slack workspace, but assuming that you can't install the gRPC extension because of your hosting provider not supporting it, for that money, I would rather suggest investing the money in a provider that does 😅

**Comment by desmeit** [comment]
Thanks anyway. I think I will find a solution. ;-)

**Comment by desmeit** [comment]
Hey, now I installed the latest version and I have still the following issue:

`Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context `

Can you please explain what exactly should be entered at "withDefaultStorageBucket"?
Is it the project ID or the project name?

**Comment by desmeit** [comment]
Okay, I got it. I have to call:

$factory = (new Factory)->withServiceAccount(__DIR__.'/google-service-account.json');

**Comment by desmeit** [comment]
Now I use the latest version but I'm not able to upload a file:

Fatal error: Uncaught Error: Call to undefined method Google\Cloud\Storage\StorageClient::upload()

**Comment by jeromegamez** [comment]
https://googleapis.github.io/google-cloud-php/#/docs/cloud-storage/v1.23.1/storage/storageclient (linked in the docs) shows you how to use the storage client. There you will find that the StorageClient has no method `upload()` (that's why you get the error), but a _bucket_ has: https://googleapis.github.io/google-cloud-php/#/docs/cloud-storage/v1.23.1/storage/bucket?method=upload

You can find a working example at https://github.com/jeromegamez/firebase-php-examples/blob/d08ed44be9191dd81dc6680adebefdcd93d2cebe/src/Command/UploadFileCommand.php#L53

**Comment by desmeit** [comment]
Okay thanks. Now I get this error:

`Uncaught Exception: Stream is not seekable in XXX/vendor/guzzlehttp/psr7/src/Stream.php on line 204`

**Comment by desmeit** [comment]
Sorry, I switched to Amazon SDK PHP and S3. Here it is working within 5 minutes.
The documentation for firebase-php is really extremely poor and when I have solved one error, the next one comes. Nevertheless, thank you.

**Comment by jeromegamez** [comment]
As soon as I've become a billion-dollar-company, I'll tackle the extremely poor docs 🤞🏼
