### ISSUE TITLE
Firebase authentication and database access

### ISSUE THREAD

**Issue by joseph-lum** [kreait/firebase-php#59]
I used the prescribed method of authentication on Firebase as below (I'm using version 1.x as I'm on PHP v 5.6 and I understand the latest firebase-php version requires PHP v 7)

```php
use Kreait\Firebase\Configuration;
use Kreait\Firebase\Firebase;

$config = new Configuration();
$config->setAuthConfigFile(__DIR__.'/google-service-account.json');

$firebase = new Firebase('https://<my-app>.firebaseio.com', $config);
$firebase->get('/');
```

At first I had a permission denied error, but after several frustrating attempts to overcome it, I decided to make my read access public, but even after doing so, I was returned with an empty json. As I understand now, I have 2 issues - the first being an authentication issue, and later on a data retrieval issue.

I have tried successfully using NodeJS and the same credentials to access the same firebase database and am quite perplexed with regard to the current issues. The difference (as I noticed) is that in NodeJS, I first initialized my firebase app with the configuration json, then authenticate myself by signing in with email and password before I proceed to retrieve data.

 Is there a possibility that version 1.x might have some peculiarities that need some special configuration?

**Comment by jeromegamez** [comment]
That's really strange, I have no clue why the same Credentials File would work in one project but not in the other, so I can only guess: Perhaps there is a protection on Firebase's side that prevents the usage of a credentials file in two different environments or at the same time.

In general I think it would be good advice to use separate credentials for separate projects, so if you haven't done so already, I suggest you create new credentials and try with them.

At this point, I don't think it's an issue with the library itself, as there haven't been changes since some time and the problem does not to be widespread among the users of the SDK.

Please let me know if you found out the reason, this is an intriguing issue.

**Comment by sq-ricardo-pereira** [comment]
Hi Guys, I've been having the same problem. Some one figured out the reason?

**Comment by jeromegamez** [comment]
If you can connect to the Firebase Database at all, it means that the service account JSON itself is valid and working.

The fact that you need to authenticate as an user (in the Node environment by entering an email and a password) is a hint that the Service Account doesn't have enough permissions by itself.

Please make sure in the Google IAM that the service account has the "Project -> Owner" Role.
