### ISSUE TITLE
When sending notification, getting an 'undefined' notification as well as the actual notification.

### ISSUE THREAD

**Issue by binnyva** [kreait/firebase-php#603]
- OS: Ubuntu 20.04.2 LTS
- PHP: 7.4.3
- Firebase SDK: "kreait/firebase-php": "^5.18"
- kreait/firebase-php        5.18.0  Firebase Admin SDK
- kreait/firebase-tokens     1.15.0  A library to work with Firebase tokens

I'm using this library to send Cloud Message - push notifications to a PWA app. Code...

```php
$factory = (new Factory)->withServiceAccount($secret_file);
$this->messaging = $factory->createMessaging();

$message = CloudMessage::fromArray([
	'token' => $token,
	'notification' => ['title' => $title, 'body' => $body]
]);

$response = $this->messaging->send($message);
```

It works - but I'm getting 2 notifications each time this is called. One notification with just the text 'undefined' - and another with the accurate notification title and body.

Response looks valid...

```
Array
(
    [name] => projects/covid-case-count/messages/MESSAGE_ID_REMOVED
)
```

Looks like a bug - or am I making a mistake somewhere?

**Comment by jeromegamez** [comment]
Your code looks fine, the response from the Firebase FCM Api as well (one item in the payload = one message received by Firebase).

Either Firebase (the service) is sending the message twice or the message handler of your client app fires twice - once without getting a value and then with the actual message.

The SDK is quite stable and in use in many big projects, the messaging parts haven't been touched in quite some while and if this were a general issue with the SDK or Firebase itself, I'm sure I would have received more support requests. So, contrary to what you said in https://github.com/binnyva/Covid-case-count/issues/1, at the current moment, I don't believe it's a library issue 😅

But I'd love to be wrong,then I could fix it 🤞. Unfortunately I was not able to reproduce the issue, especially since a simple `Undefined` cannot be sent from the SDK and I have never seen it being sent from Firebase (the service) as well 🤔

**Comment by binnyva** [comment]
I see. I'll investigate a bit more - but my code right now is too simple to have any issue. Another possibility is its a issue in Chrome - but again, doubtful. Anyway, thanks for your time. I'll close the issue for now - let you know if I have any more details.

In the mean time, I'll leave a screenshot of what the issue looks like - in case you get more such issues you can recognize it...

![WhatsApp Image 2021-05-06 at 10 33 38 AM](https://user-images.githubusercontent.com/8948/117244747-3cc71580-ae57-11eb-8941-c3aee614c9a8.jpeg)
