### ISSUE TITLE
Return value of Kreait\Firebase\Exception\ApiException::getPreciseMessage() must be of the type string, array returned

### ISSUE THREAD

**Issue by iamakanksha** [kreait/firebase-php#616]
#### System information 
Operating system: Ubuntu 14
PHP version: 7
kreait/firebase-bundle: 1.2.1                    
kreait/firebase-php: 4.18.0                       
kreait/firebase-tokens: 1.7.2                        
kreait/gcp-metadata: 1.0.1     
Symfony-bundle: 2.8

#### Error message returned
**TypeError**
Return value of Kreait\Firebase\Exception\ApiException::getPreciseMessage() must be of the type string, array returned

#### Code snippet throwing the error 
![image](https://user-images.githubusercontent.com/49341160/118926956-ba624980-b95e-11eb-93f2-a6d7a1f599c8.png)

 @jeromegamez

**Comment by jeromegamez** [comment]
Version 4.18 is a really old version that I definitely cannot provide support for. Please update the SDK to 4.44 (the latest 4.x release) and let me know if the problem remains.

If so, it would also help if you included an example so that I can reproduce the problem. All I see at the moment is an error message, and I can't just guess why it might happen 😅
