### ISSUE TITLE
Firebase Cloud Storage File Upload and Download 

### ISSUE THREAD

**Issue by imselmon** [kreait/firebase-php#668]
### Describe the feature you would like to see

Firebase Cloud Storage File Upload and Download

**Comment by jeromegamez** [comment]
The documentation includes links to the official Google Cloud Storage PHP Library docs where storing and retrieving files from Google Cloud Storage is described, specifically:

* https://googleapis.github.io/google-cloud-php/#/docs/cloud-storage/storage/bucket?method=upload
* https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/storage/src (the examples starting with `upload_*`

Since this SDK only provides a bridge to the official Google Cloud Storage PHP Library, documenting all that's possible with it is out of the scope of this SDK - it would just be too much work to keep it all in sync, sorry 🙏

**Comment by imselmon** [comment]
I tried to upload using our sdk and it's working without the cloud PHP storage sdk
