### ISSUE TITLE
Maybe I'm missing something?

### ISSUE THREAD

**Issue by derekbtw** [kreait/firebase-php#67]
The documentation is really frustrating me. It just assumes you know what you're doing.. lol.  I'm referring to the last step which says,

 "After installing, you need to require Composer’s autoloader:
`require 'vendor/autoload.php';`"

...Where??? WHERE do you require it? seems like a pretty big oversight for people who are new to PHP.

**Comment by x1nixmzeng** [comment]
You add the header as you would any other, at the top of your PHP scripts.

So an entire example would be:

```php
require_once '../vendor/autoload.php';

$firebase = Firebase::fromServiceAccount(__DIR__.'/google-service-account.json');
$database = $firebase->getDatabase();

$newPost = $database
    ->getReference('blog/posts')
    ->push([
        'title' => 'Post title',
        'body' => 'This should probably be longer.'
    ]);

$newPost->getKey(); // => -KVr5eu8gcTv7_AHb-3-
$newPost->getUri(); // => https://my-project.firebaseio.com/blog/posts/-KVr5eu8gcTv7_AHb-3-

$newPost->getChild('title')->set('Changed post title');
$newPost->getValue(); // Fetches the data from the realtime database
$newPost->remove();
```

This assumes you've run `composer update` which produces other local files, `composer.json`, `composer.lock`, and the `vendor` folder.

**Comment by jeromegamez** [comment]
@derekbtw Thanks for reaching out instead of just walking away with frustration, I really appreciate it, and I have added the `<?php` header and `require` statements to the examples in the docs.

Setting up und using composer is not necessarily in the scope of this library, but this is how you would get started from scratch, assuming that you are on MacOS or a Linux system:

```bash
mkdir my-project && cd my-project
# Download and install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
# You should now have a `composer.phar` file in the current directory
# It's common to put composer in a globally accessible path for convenience
mv composer.phar /usr/local/bin/composer
# From now on, you can just invoke "composer" from any path
# Now, require the Firebase Admin SDK for PHP
composer require kreait/firebase-php
# You will now have a composer.json file in your current directory
# as well as a "vendor" directory, in which composer puts all
# project dependencies
```

You can now create a new file, e.g. `firebase.php` in the current directory

```php
<?php

require __DIR__.'/vendor/autoload.php';

$firebase = Firebase::fromServiceAccount(__DIR__.'/google-service-account.json');
```

from which you can continue. Please note that in this example, you also need a Google Service Account credentials file as described at http://firebase-php.readthedocs.io/en/latest/authentication.html#with-a-google-service-account in the same directory as the `firebase.php` file. And PHP 7, of course.

If you followed all the steps, you should have the following files in your directory:

```
~/my-project
├── composer.json
├── composer.lock
├── firebase.php
├── google-service-account.json
└── vendor
```

If you don't have PHP 7 on your system (MacOS ships with 5.6, as far as I know), you can install it with [Homebrew](https://brew.sh), see https://github.com/Homebrew/homebrew-php - or a VM running PHP 7.0 (which is a story by itself :))

**Comment by jeromegamez** [comment]
I will close this issue now, because it is not directly related to the library, but feel free to add further comments if something remained unclear. If you'd like, feel free to join us in the [Firebase Slack Community](https://firebase-community.appspot.com/) in the #php channel - there are more people that certainly would like to help!

**Comment by derekbtw** [comment]
Thanks guys! I appreciate it a lot!

**Comment by murtraja** [comment]
@jeromegamez , Can you link [your comment](https://github.com/kreait/firebase-php/issues/67#issuecomment-285973508) in the main Readme so that it is easier for composer beginners like us?

Also, since the comment is old, if possible, can you update the steps and post. I am finding it very hard to get started with this awesome library!
