### ISSUE TITLE
How to used it without composer in wordpress

### ISSUE THREAD

**Issue by parth-mangukiya** [kreait/firebase-php#690]
### Describe the feature you would like to see

Hello there,
A WordPress Developer,
unfortunate i can't use composer in my WP project i need to include  your admin php sdk without composer is there any way?

Hope you understood the issue..
Thank in advance.

**Comment by jeromegamez** [comment]
Using composer is the only supported way, because the SDK pulls in 3rd-party-dependencies and composer makes sure that all of them are conflict-free with other dependencies that might be present in a project.

What you could do is using composer locally or in the build pipeline, if available, upload the vendor directory to your server, and make sure the vendor/autoload.php file is included in your autoloading setup.

Another possibility could be to use a project like https://roots.io/bedrock/ to enable your WordPress project to use composer natively.

However, I can't provide free support for that, I hope you can understand.
