### ISSUE TITLE
Automatically set APNS content-available when using withHighestPossiblePriority() in data only notifications

### ISSUE THREAD

**Issue by leonardomdr** [kreait/firebase-php#700]
### Describe the feature you would like to see

When you send data only notifications to iOS devices with apns-priority set (10 or 5), you face this error: "Request contains an invalid argument." (INVALID_ARGUMENT). Debugging the response you will find: "Invalid registration token".

The error text is really a mess, and can make you lose hours to find a solution. 

In this case, if you want to keep the high priority it's necessary to set "aps -> content-available" (1 or 0) in the APNS config payload.

My suggestions are:
1. Identify this error and treat it to point to a solution, helping future users that may face this error.
2. Automatically include the "aps -> content-available" field in the APNS config payload if it's a data only notification.
3. Create a argument in the "withHighestPossiblePriority()" for you to specify the "content-available" value (true/false). Example: "withHighestPossiblePriority($content_available = false)".

I'm open to other solutions. It's just a suggestion/feature request. 

Right now I'm doing like this:

// This sample will get "Invalid registration token" error.
`$message = CloudMessage::withTarget("token", $token)
                ->withData($data)
                ->withHighestPossiblePriority();`

// This will work and process the notification immediately in the device
`$message = CloudMessage::withTarget("token", $token)
                ->withData($data)
                ->withHighestPossiblePriority()
                ->withApnsConfig(["payload" => ["aps" => ["content-available" => 1]]]);`

**Comment by jeromegamez** [comment]
Thanks for the detailed description, I really appreciate it!

Unfortunately, I couldn't reproduce the problem - I used the same code that you provided as not working, at least I think so, can you confirm that the added test in #701 is the same that caused you the issue?

Perhaps the issue is that I don't have an iOS device at hand to generate a registration token for it, so perhaps that's the reason.

If I continue to not be able to reproduce the problem, could you point me to the documentation that states that both config settings need to be set?

Last question (for now, I promise :D): which version of the SDK are you currently using? If it's not 6.x, please try updating the dependency, just to make sure it's not just something in the 5.x branch of the SDK 🤞

**Comment by leonardomdr** [comment]
You're welcome. I took some extra time on this message because I lost almost 5 days on this.

It only happens in real devices. You can't test this in a simulator. In iOS simulators you get a FCM token, but internally there's no APNS token registered, and then, because of that, when you send a message to Firebase it returns a success status code.

The test you have added is exactly the same that is causing the issue here. The only thing that you need to make sure, is that the token provided is from a real iOS device, then you will face the error.

I was at version 5.19 first, but when I discovered the issue, I have updated the package to the latest version (6.3.1) to test again before creating this message. So the error is happening in version 6.x as well.

About the documentation, these are the links that led me to this conclusion:
- https://rnfirebase.io/messaging/usage#data-only-messages ("Data only messages" whole section)
- https://firebase.google.com/docs/cloud-messaging/http-server-ref (search: content_available)

But now, searching a little bit more, I found this:
- https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

Which states:

> To send a background notification, create a remote notification with an aps dictionary that includes only the content-available key, as shown in Listing 1. You may include custom keys in the payload, but the aps dictionary must not contain any keys that would trigger user interactions.

But, it does not mention that it would trigger "Invalid registration token" error. And to be honest, this error is really misleading, maybe that's the reason there's no direct documentation about this, haha.

Hope it helps.

**Comment by jeromegamez** [comment]
Thanks for the details! Since I currently can't test this with a real device (I would probably need an Apple Developer Subscription and an App to test this), are you willing to give the code in the PR a try to confirm that it works, once I've decided on a way to handle this?

**Comment by leonardomdr** [comment]
Sure. Just let me know and I can test it when it's ready.

**Comment by jeromegamez** [comment]
The issue is, unfortunately, not as easy to tackle as I initially thought, so it will take me a while longer, but I'll let you know once I have something.

While looking things up, I also noticed that the 

```php
$message = CloudMessage::withTarget("token", $token)
    ->withData($data)
    ->withHighestPossiblePriority()
    ->withApnsConfig([
        "payload" => [
            "aps" => [
                "content-available" => 1
            ]
        ]
    ]);
```

only seemingly works - when you call the `withApnsConfig` method, the previous priority setting is voided because the ApnsConig is injected in full. It's good that it worked out in your case, but I'm afraid it's just a coincidence.

Testing if it's a data-only message is also not trivial - the `ApnsConfig` doesn't know if the parent `CloudMessage` has a notification set or not, so I have to come up with something and that will probably require rewrites in several locations.

The good news is: it's good that you updated to 6.x because I will probably not make the same changes in 5.x if I come to a solution.

**Comment by leonardomdr** [comment]
I believe it's not a coincidence because I've done my firsts tests at the Firebase explorer. 
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send

I've recorded the video below for you to see the behaviour. The token in the video is a valid token from a real iOS device.

https://user-images.githubusercontent.com/13877036/169565828-9e6b7b8f-2333-4e33-ab4a-9819e4234535.mp4

You can see in the video that if I only set the apns-priority to 10 in the headers without the content-available in the payload, it fails with that weird "Invalid registration token" error.

**Comment by jeromegamez** [comment]
Oh, I'm afraid I didn't express myself well enough (non native speaker here 👋). It's not a coincidence that Apple's requirement are as they are, just how the SDK is implemented and how it behaved. I recognize the problem, I'm just saying it will take me a while 😅

**Comment by leonardomdr** [comment]
Hahha, it's fine. I probably misunderstood you (non native here as well).

About the timing, no problem. Thank you.

**Comment by jeromegamez** [comment]
Could you have a look at #701 and test if it works for you? I'd be grateful if you could provide your feedback directly on the PR 🙏

**Comment by beliven-michele-brandolin** [comment]
This would fix exactly my problem too. I'm going to test it asap.
Do you have any plans for releasing it ? Thanks

**Comment by jeromegamez** [comment]
@michele-brandolin-heply As soon as you or @leonardomdr can confirm that it works, I'll merge the PR and create a new release 💪🤞

**Comment by leonardomdr** [comment]
Just tested it right now and replied in the PR.
