### ISSUE TITLE
Cant update without removing old values

### ISSUE THREAD

**Issue by kiwo12345** [kreait/firebase-php#72]
When I upload an new item into my app I also save the item in firebase like this:

```
app('firebase')->getDatabase()->getReference('item/'.$newPost->post_id)->set([
           'total_views' => 0,
           'title' => $request->input('title'),
           'user_id' => $newPost->user_id,
      ]);
```

I dont use `Push()` since I want to set my own unique key.

This works a new record is created but the problem is when I later try to update that record:

```
$updatePost = [
                  'title' => $request->input('title'),
              ];
              app('firebase')->getDatabase()->getReference()->update(['item/'.$postId => $updatePost]);
```

This will update the items title, but it will also remove the fields **total_views** and **user_id** which I dont want.

So how can I update specific fields in a record without removing other fields in that same record?

**Comment by jeromegamez** [comment]
That's because you are working with the root reference as a base instead of working with the `post` reference. I suggest doing it like this:

```php
$updatePost = [
    'title' => $request->input('title'),
];

app('firebase')
    ->getDatabase()
    ->getReference('item/'.$postId)
    ->update($updatePost);
```

This has the advantage that, if something should go wrong, the problems are limited to the scope of the reference instead of your whole data.

---

An alternative could be to set the field directly:

```php
app('firebase')
    ->getDatabase()
    ->getReference('item/'.$postId.'/title')
    ->set($request->input('title'));
```

---

If you want to continue working on the root reference, you have to update your `$updatePost` variable:

```php
$updatePost = [
    'item/'.$postId.'/title' => $request->input('title'),
];

app('firebase')
    ->getDatabase()
    ->getReference()
    ->update($updatePost);
```

As I said, I don't recommend this, I'm just adding it for completeness.

**Comment by kiwo12345** [comment]
@jeromegamez Thanks for explaining it. I switched to your first example and everything works fine now!
