### ISSUE TITLE
Defining path in a nested folder other than root folder

### ISSUE THREAD

**Issue by prantikv** [kreait/firebase-php#76]
Referring to this issue [here ](https://github.com/kreait/firebase-php/issues/67) this might be something trivial.

I have a PHP project where I have the following structure
/my-project
├── composer.json
├── composer.lock
├── index.php
├── google-service-account.json
└── vendor(folder)
**└── includes(folder)
└── └── functions.php**

Notice the includes folder which has the functions.php file in it. Inside the fuctions.php file I want to use firebase, so I am referensing it as follows,
`
require __DIR__.'/vendor/autoload.php';`

Composer has installed the dependencies in the root folder i.e, my-project. So I am getting the following error

>  Warning: require_once(../vendor/autoload.php): failed to open stream: No such file or directory in 

What is the proper way to refernce the firebase file inside a nested folder?

**Comment by jeromegamez** [comment]
Inside your `functions.php`, you have to use the following line:

```php
require __DIR__ . '/../vendor/autoload.php';
```

[The magic `__DIR__` always points to the directory of the file you're currently in](http://php.net/manual/en/language.constants.predefined.php#constant.dir) - that's why you have to move one folder up from the `includes` directory (`..`) to be able to enter the `vendor` dir.

I hope this helps!

**Comment by jeromegamez** [comment]
Just in case you have used the following in your `index.php`:

```php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/includes/functions.php';
```

In this case, you don't have to re-include the `autoload.php` inside the `functions.php`.


You might want to consider using [`require_once`](http://php.net/require_once) instead of [`require`](http://php.net/require), depending on your use case.

**Comment by prantikv** [comment]
Yes, I solved it by getting the current working directory as follows
```
$path= getcwd();
require_once $path.'/vendor/autoload.php';
```
