### ISSUE TITLE
Php 8.1 support for Windows

### ISSUE THREAD

**Issue by george-kar** [kreait/firebase-php#770]
### Describe the feature you would like to see

Hello, I want to use laravel-firebase in Windows environment with Php 8.1. Unfortunatelly, your package requires lcobucci/jwt 4.2-4.3 which requires ext-sodium which is not available on windows php 8.1 (only 7).

Can you make your package compatible with windows php 8 as well?

**Comment by jeromegamez** [comment]
The Sodium extension has been bundled with PHP since PHP 7.2, so, unfortunately, I don't know why it doesn't work on your Windows machine.

https://www.php.net/manual/en/sodium.installation.php

I'm afraid I can't remove the current `lcobucci/jwt` dependency from the SDK, but if it's not possible to make it work in your environment, you could try if it works with [version 6.x of this SDK](https://github.com/kreait/firebase-php/tree/6.x) and pinning `lcobucci/jwt` to `4.1.*`.

Since this is not an issue that I can fix in code, I'm going to close the issue now, but feel free to add further comments with your findings so that others might benefit from them if they stumble upon this issue while doing their research.

**Comment by george-kar** [comment]
It looks like that Sodium is part of 8.1 already with no extra download required. It only take one line on the php.ini and it runs.
Sorry for the mess.

**Comment by jeromegamez** [comment]
No problem! 🙌
