### ISSUE TITLE
Group Notification 

### ISSUE THREAD

**Issue by beshoo** [kreait/firebase-php#793]
### Describe the feature you would like to see

I have a question about web push notifications. I'm wondering if there's a way to send multiple notifications to the same user without overwhelming them with too many notifications. I mean send the notification in group!

Can you help me understand if this is possible and how it can be done in a way that respects the users' experience?

![image](https://github.com/kreait/firebase-php/assets/4635115/07ab1e41-0c35-4895-b008-de43be73d2c2)

**Comment by jeromegamez** [comment]
I'm sorry, but that's not a question related to this SDK but how messages should be composed to achieve a certain behavior on the client.

Based on your screenshot you're talking about Android notifications, not WebPush notifications. You probably want to dive into the [concepts of FCM Messages](https://firebase.google.com/docs/cloud-messaging/concept-options), especially [(Non-)Collapsible message](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages).

Other than that, I'm afraid I can't provide free, individual support, I hope you understand.

Since this is not an issue with the SDK, I'm going to close the issue but feel free to add your findings so that others might benefit from them.

**Comment by beshoo** [comment]
**Delivery options**
FCM provides a specific set of delivery options for messages sent to Android devices and allows for similar options on Apple platforms and web. 

For example, "collapsible" message behavior is supported on Android via FCM's collapse_key, on Apple via apns-collapse-id, and on JavaScript/Web via **Topic**. For details, see descriptions in this section and related reference documentation.

Sourcs: [Goole Doc](https://firebase.google.com/docs/cloud-messaging/concept-options#:~:text=Send%20Requests.-,Delivery%20options,to%20the%20mobile%20app%20to%20contact%20the%20server%20to%20fetch%20data.,-FCM%20does%20not)

How can we send a topic "collapsible" message!
