### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by arstropica** [kreait/firebase-php#817]
### Describe the feature you would like to see

It would be great if a minimum release version could be included in the main README.
I have a production server on PHP 7.2 and I don't know whether release 5.19.0 of firebase-php, which is the latest version that is compatible with v7.2, will work with the Firebase api.
Does anyone know whether 5.19.0 still works?
Thanks.

**Comment by jeromegamez** [comment]
Thanks for bringing this up, it's a fantastic idea! I will add a supported versions table to the README.

Here's roughly what it will contain (I'm using this response as my initial draft, non-binding of course 😅).

I actively maintain (add features and fix bugs) only the **latest** version (currently 7.x). The latest version supports actively supported PHP versions (currently 8.1 and 8.2).

The **previous** version (currently 6.x) will receive security fixes as long as its lowest PHP requirement receives security fixes. For 6.x, this means that security support ends on 2023-11-26.

I do not support and do not add features, restore broken functionality or bugfixes to other/older versions unless a request is from a GitHub sponsor with a certain $-tier, or attached with the offer to pay an invoice 😅. This will require the requester to agree that the implemented changes/additions are made available to the community.

I also do not provide free 1:1 support, especially not in non-public channels (that's not addressed to you, but I receive such emails quite often).

To come back to your original question: I don't support version 5.x anymore. The problem here is that I shouldn't have used such a wide PHP version constraint, that's why you're stuck with an old feature release of this old version.

That being said: Although older versions obviously have less features, they _should (:tm:)_ work, unless Firebase has removed APIs.

I do, of course, recommend upgrading to a supported PHP version, but I also understand very well that this isn't always possible in (especially large, mostly commercial) legacy projects. In that case, I would point to the "Sponsor or Invoice" paragraph. This project is used in many, many commercial projects, and I don't have the resources for unpaid work.

I know you didn't expect such a long response with information you didn't ask for, but I hope for your understanding!

**Comment by drupol** [comment]
It's also very nice to have such a compatibility matrix for distributions packagers (like me), so, thanks for this :)

**Comment by arstropica** [comment]
Thank you for making such a thorough response to my request.  Fortunately, my sysops has agreed to upgrade the PHP version on our production server. But in any case, I really appreciate the work that you are doing.
Grüß Gott!

**Comment by jeromegamez** [comment]
The readme now includes a supported versions table, thanks again for your suggestion!

**Comment by arstropica** [comment]
Thanks! Very clear and informative.
