### ISSUE TITLE
firebase-php authentication

### ISSUE THREAD

**Issue by theunreal** [kreait/firebase-php#89]
I believe it's the right place for this discussion as soon as it's directly releated to this library auth usage and lack of information about using firebase-php to retrieve user data.
If you believe it's a wrong place for this kind of discussion, please close this issue.

This is a typical scenario, and I wonder if i'm doing it right.
I used [jwt-auth](https://github.com/tymondesigns/jwt-auth/wiki/Installation) before, and the proccess looked like this:

1. User logs in, server returns a jwt token.
2. Every API call is sent along with the jwt token
3. Converting token to user information using `$user = JWTAuth::toUser($token)`

Using firebase-php, it's very unclear to me about how the proccess flow should look like.

1. Use logs in (client).
2. client sends http request to the server with the auth uid (?)
3. Server checks if user exists (storing and querying for the auth uid?):
3.1 if not, register and return user data.
3.2 if exists, return user data.

Any ideas?

**Comment by jeromegamez** [comment]
Hey @theunreal, and thank you for the detailed description of your use case.

The reason why you can't find any information on how to retrieve user data using firebase-php is because the functionality isn't there - otherwise it would be documented :).

One reason why I haven't started looking deeper on this is because the REST API enabling this functionality has a big red box on top of it which doesn't make clear whether the API is still supported or will continue to be supported in the future: https://developers.google.com/identity/toolkit/web/reference/

It is of course possible to use it and @waleedazam has shared his approach in https://github.com/kreait/firebase-php/issues/35#issuecomment-252562092 which I recommend you to check out - perhaps you can use this as a base to realize your use case.

What firebase-php, in its current state, can provide, is this variant of your workflow:

1 + 2: User logs in (client) (see https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients)

```javascript
firebase.auth().currentUser.getToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});
```

3. The server receives the ID-Token and verifies that it is valid (see https://firebase-php.readthedocs.io/en/latest/authentication.html#working-with-tokens)

```php
use Kreait\Firebase\Factory;

$firebase = (new Factory())
    ->withCredentials('...')
    ->create();

$idTokenString = '...'; // The token from the client

$idToken = $firebase
    ->getTokenHandler()
    ->verifyIdToken($idTokenString);

$uid = $idToken->getClaim('sub');
```

When you got to the point that you have the `$uid` token, you know that the ID-Token is valid and can be used to [perform requests to the Realtime Database with the permissions of this user](https://firebase-php.readthedocs.io/en/latest/authentication.html#impersonating-users):

```php
$reference = $firebase
    ->asUserWithClaims($uid, [])
    ->getReference('/path/to/location');
```

Now that you can be sure that the ID token is actually from the user, you could also use it to retrieve data about the user that you have stored in the realtime database - in case you do store such data in the database:

```php
// Fictional reference
$profileData = $firebase->getReference('/users/'.$uid.'/profile')->getValue();
```

As much as I understand your and other's need to have this functionality: we don't have it at the moment. That doesn't mean that it will not be here some time in the future ([the official NodeJS-SDK can do this as well](https://firebase.google.com/docs/auth/admin/manage-users#create_a_user) and seems to be using the Identity Toolkit to do so), but I can't give you a timeline on that.

I assume you would have preferred an actual "lack of information/documentation" to my "not possible (yet)", but please be assured that I take your request and use case seriously (as I did all the other times other developers have brought it up), and will move this up on my todo list, which I hopefully can get to in the near future. No promises though :)

**Comment by theunreal** [comment]
Hi @jeromegamez, I really appreciate your awesome contribution and detailed answers here!

My intention wasn't about new library feature, my intention was to discuss about the right use case.
I also have no intention using the firebase real time database, only the authenticating.
My goal is to store the user data in my own server, not in the real time database - and my question comes from here.
What i'm trying to achieve is to authenticate users with firebase while saving the user data to my own server.
I'm not sure sending a post request with the auth data received by the client is a good practise.

**Comment by jeromegamez** [comment]
Firebase has recently open sourced many of their SDKs, and I will certainly get many hints from what they are doing. What I have seen is that they are in fact using the Identity Toolkit as well, so I will do so, too :)

**Comment by MGParisi** [comment]
Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase::getTokenHandler() in C:\wamp64\www\nwraptrax\secure.php:25 Stack trace: #0 {main} thrown in C:\wamp64\www\nwraptrax\secure.php on line 25

Your above code returns this ^^^^^^  Sorry, but it doesn't seem to work...

**Comment by MGParisi** [comment]
This also errors...

Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase\Factory::withCredentials() in C:\wamp64\www\nwraptrax\secure.php:13 Stack trace: #0 {main} thrown in C:\wamp64\www\nwraptrax\secure.php on line 13
