### ISSUE TITLE
Problem with composer install

### ISSUE THREAD

**Issue by kop** [kreait/firebase-php#9]
Something is wrong with `egeloen/http-adapter` dependency:

```
  Problem 1
    - Installation request for kreait/firebase-php ~0.4 -> satisfiable by kreait/firebase-php[0.4.0].
    - kreait/firebase-php 0.4.0 requires egeloen/http-adapter dev-feature/tape-recorder-subscriber as 0.5 -> no matching package found.
```

**Comment by jeromegamez** [comment]
Thanks for the heads up, @kop, I will fix that this afternoon, this evening at the latest.

**Comment by jeromegamez** [comment]
Could you try the latest release (0.4.1) please? I am quite optimistic that this should fix the issue.

BTW, the next pre-release version will introduce breaking changes - the API will be changed so that it matches the JavaScript-API, but if you rely on the current implementation, I would make the current calls deprecated first.

**Comment by kop** [comment]
Thank you, @jeromegamez, it works now.

As for me, I'm ok with breaking changes - I'm aware of them and will be able to update the code quickly. But for other guys who might use this extension, I think it would be better to go with a semver and introduce breaking changes in 1.x.x branch.

Anyway, thanks for a nice package :)

**Comment by jeromegamez** [comment]
It's my pleasure, especially because you are the first person that I know of using this, yay! ❤️
