### ISSUE TITLE
Send FCM push notifications to iPhone Simulator

### ISSUE THREAD

**Issue by FrazeColder** [kreait/firebase-php#907]
### Describe the feature you would like to see

Hey there,

thank you for the awesome package!

Is it also possible to send FCM push notifications to iPhone Simulator?
Here, I found how to archive that: https://stackoverflow.com/questions/66040828/can-you-receive-fcm-push-notification-from-ios-simulator

But how can I archive this with this package?

Kind regards

**Comment by jeromegamez** [comment]
As far as I know, this is not possible. For this SDK it wouldn't make a difference, as it only sends messages to registration tokens via the Firebase APIs and Firebase handles the delivery.

To be sure, please contact Firebase support, they will certainly be able to confirm whether or not this is possible. If you do, please share your findings here so that others can benefit from them 🙏🏻
