### ISSUE TITLE
Issue with Laravel 8

### ISSUE THREAD

**Issue by IguchiShigeru** [kreait/firebase-php#941]
### Describe the feature you would like to see

I am using Laravel 8.x and laravel-firebase 4.1. I have a bulk sending function that uses the sendMulticast() function. However, I am facing an issue similar to this one (https://github.com/kreait/laravel-firebase/issues/231).

I cannot upgrade Laravel 8 to 10 because I need to use other libraries as well. However, if I don’t upgrade, I cannot install the laravel-firebase 5.x version.
How can I fix this issue without upgrading Laravel?

**Comment by jeromegamez** [comment]
You could try updating the bundle and SDK with ignoring the platform dependencies, but that's not something I would recommend, and if you're not on PHP 8.1, it wouldn't work anyway.

Another way would be to fork the package and SDK and try to backport the functionality - but doing this would probably require so much time, it might be better spent to replace the outdated other dependencies or contribute to them so that they work with newer Laravel/PHP versions.

You can still loop through each message one by one and use the "normal" `send()` method instead of the `sendAll()` or `sendMulticast()` methods, but if you're sending a lot of messages I would recommend deferring the sends to a queue and workers, otherwise it will take forever.

Finally, you could let me try the backporting, but this is going to be expensive, since your Laravel version is really, really old 😅
