### ISSUE TITLE
Using firebase-php with Composer

### ISSUE THREAD

**Issue by emartos** [kreait/firebase-php#96]
Hi there,

I'm trying to use the component in my project using Composer instead of source code. I've installed version 2.x.

Following the [docs](http://firebase-php.readthedocs.io/en/2.x/), I'm unable to make it work:
```

require __DIR__.'/vendor/autoload.php';

$firebase = (new \Firebase\Factory)
    ->withCredentials(FIREBASE_CREDENTIALS)
    ->withDatabaseUri(FIREBASE_URI)
    ->create();

```
I get **PHP Fatal error:  Uncaught Error: Class 'Firebase\Factory' not found**. Am I missing anything?

Thank you in advance!

**Comment by jeromegamez** [comment]
Hi! That's really strange - what do you mean with "composer instead of source code"? Could you please make a `composer show` from the root of your project, just to be sure that you are indeed using version 2.x?

The thing is: if you're using PHP 7+, I would highly recommend using the latest release (3.x) - if you're on PHP 5.6, Release 1.x is your only option, and it has a different API.

Please let me know if you found something out!
